### ISSUE TITLE
Running ARM Applications on SteamOS 3.5.6

### ISSUE THREAD

**Issue by donlinglok1** [ryanrudolfoba/SteamOS-Waydroid-Installer#1]
Hi, i really like you project because it is easy to follow and help me successfully install waydroid. However, i found that i cannot download some game in Google Play. After some check i found casualsnek script, and yes in the end i realize you already tested and write on the README.md.

In my point of view, i think the problem is SteamOS 3.5.6 in someway mounted the `/var/lib`, so i try to change `/var/lib/waydroid` to `/usr/local/games/waydroid` in your install script but DON'T try it because more problem(some path still cannot change in waydroid arg.work). 

I guess i can still enjoy the waydroid with only x86. After all, appreciate for all you work. Thank you.

**Comment by ryanrudolfoba** [comment]
Hi thank you for your feedback. I'll poke around using your method.

**Comment by ryanrudolfoba** [comment]
What game is that let me try on waydroid

**Comment by ryanrudolfoba** [comment]
arm applications now work in the latest script

**Comment by soapproject** [comment]
Hi, have you launch BA successfully?
I face the same issue here with last script.
https://github.com/waydroid/waydroid/issues/788

**Comment by brokenwingsx321** [comment]
> > Hi, have you launch BA successfully? I face the same issue here with last script. [waydroid/waydroid#788](https://github.com/waydroid/waydroid/issues/788)
> 
> sorry, I only success to run BA using genymotion but it feels slow. I didn’t try waydroid yet.

Hi could you go through your steps of installing blue archive on genymotion? It always gives me a arm translation error.

**Comment by brokenwingsx321** [comment]
> It's long time ago and i don't have any record on it, you may refrence here: https://github.com/m9rco/Genymotion_ARM_Translation and here to resize storage https://www.reddit.com/r/linux4noobs/comments/bj7ezk/genymotion_increase_internal_storage_space/
> 
> However, genymotion performance is not good, i just give up and use Bluestack on my PC after all.
> 
> I think you can try this repo to use Waydroid for the android game too, the performance should be better. https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
> 
> > > > Hi, have you launch BA successfully? I face the same issue here with last script. [waydroid/waydroid#788](https://github.com/waydroid/waydroid/issues/788)
> > > 
> > > 
> > > sorry, I only success to run BA using genymotion but it feels slow. I didn’t try waydroid yet.
> > 
> > 
> > Hi could you go through your steps of installing blue archive on genymotion? It always gives me a arm translation error.

Yeah I've tried it on waydroid it just crashes on launch every time

**Comment by gagantous** [comment]
> It is hard to said which one is better, let me run a benchmark.
> 
> Anyway now i can play the arm game. ![image](https://private-user-images.githubusercontent.com/6138806/286296901-180a619a-ba0b-4651-b5a1-b7a527aef761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODkzNjEsIm5iZiI6MTcwOTM4OTA2MSwicGF0aCI6Ii82MTM4ODA2LzI4NjI5NjkwMS0xODBhNjE5YS1iYTBiLTQ2NTEtYjVhMS1iN2E1MjdhZWY3NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMTQxNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc5YzQ0ZDliZDM0YWJkNTIwZjQ4MmM4OTg1OGY1MGI4NzgyYWIzMmY1MzhhM2QwZThlOGFhYzJhMDEzMWFkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QD-niK1xXSdYQp68-oFNuBjjO_sWw9DhEV-dpdGS29s)

Hi @donlinglok, sorry to asked you about this. I am curious about how could you run that game using genymotion? I tried to install in genymotion and it has the same problem with waydroid. What ARM did you used ? I thought ARM in genymotion only support ARM 9. While blue archive only support ARM 11+

**Comment by brokenwingsx321** [comment]
> > > It is hard to said which one is better, let me run a benchmark.
> > > Anyway now i can play the arm game. ![image](https://private-user-images.githubusercontent.com/6138806/286296901-180a619a-ba0b-4651-b5a1-b7a527aef761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODkzNjEsIm5iZiI6MTcwOTM4OTA2MSwicGF0aCI6Ii82MTM4ODA2LzI4NjI5NjkwMS0xODBhNjE5YS1iYTBiLTQ2NTEtYjVhMS1iN2E1MjdhZWY3NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMTQxNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc5YzQ0ZDliZDM0YWJkNTIwZjQ4MmM4OTg1OGY1MGI4NzgyYWIzMmY1MzhhM2QwZThlOGFhYzJhMDEzMWFkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QD-niK1xXSdYQp68-oFNuBjjO_sWw9DhEV-dpdGS29s)
> > 
> > 
> > Hi @donlinglok, sorry to asked you about this. I am curious about how could you run that game using genymotion? I tried to install in genymotion and it has the same problem with waydroid. What ARM did you used ? I thought ARM in genymotion only support ARM 9. While blue archive only support ARM 11+
> 
> base on https://github.com/m9rco/Genymotion_ARM_Translation I think i did install ARM 9 at that time. with Google Nexus 10 and Android 9?
> 
> and i did't download it on google play, i just use apk to install. https://apkpure.com/blue-archive/com.nexon.bluearchive

When I try Arm 9 it tells me it doesn't support even if I use the APK

**Comment by gagantous** [comment]
Did you install your genymotion on certain distro Linux like mint or maybe MAC? Or it still on SteamOS?

**Comment by brokenwingsx321** [comment]
> Did you install your genymotion on certain distro Linux like mint or maybe MAC? Or it still on SteamOS?

I'm using bazzite os

**Comment by gagantous** [comment]
> > Did you install your genymotion on certain distro Linux like mint or maybe MAC? Or it still on SteamOS?
> 
> I'm using bazzite os

owhh that's why, other distro linux (kind of) support dependancy for arm 11. While genymotion on steamOS not.
thanks for the reply
