### ISSUE TITLE
2 things. Pyclip and external monitor.

### ISSUE THREAD

**Issue by mikmikmikmik** [ryanrudolfoba/SteamOS-Waydroid-Installer#10]
1. Something about pyclip not being there. I got this message on the console. Can't remember where.
2.  Like the nested desktop issue I posted into the steam community forum, trying to use this on an external monitor and the pointe cannot get below a certain point in the external screen to press any of the bottom three icons. I guess it's a more general issue since it seems to happen on both this and the nested desktop. It's a pain cos I have to stop the app, unplug my monitor, start the app, and plug my monitor into the docking station again.
The normal switch to desktop has no issues with the mouse pointer going down far enough.
I can launch waydroid inside the normal "Switch to desktop". Of course, it opens in a window and I can get to the three bottom buttons in that window.
However if I try to expand that window, I see your background pic but the android display itself does not expand. Unfortunately every keypress on my Bluetooth keyboard registers as 2 presses inside waydroid on this normal desktop, and the steam virtual keyboard doesn't register at all, and core keyboard won't come up at all for me after I installed it. The android onscreen keyboard however does work.

**Comment by mikmikmikmik** [comment]
The pyclip message comes up when the container is first started or whatever the line is after the container start line.
The display issue can be fixed by pressing Steam button, going into Game details, going over the whole way to the right to the cog wheel and changing the resolution there to "native" or maybe something else.
When you exit the waydroid or the nested desktop(which is stuck at 1280x800 in this method) and then starting it up again, the mouse pointer seems to be able to go to the bottom of the external screen now, and still works after a steamdeck restart.

**Comment by ryanrudolfoba** [comment]
I ddint add pyclip in the script as it needs a lot of dependencies. and its also just used for the waydroid clipboard service i dont think it is critical to have it.

If you are using a mouse on Nested Desktop hooked up to external display that is expected behavior. Nested Desktop is hard coded to use 1280x800 resolution.
