### ISSUE TITLE
[BUG] After running the waydroid script it stops apps in desktop mode from opening

### ISSUE THREAD

**Issue by EMafini** [ryanrudolfoba/SteamOS-Waydroid-Installer#105]
After successfully loading waydroid i went back to desktop mode and some of my flatpacks were unable to fully load up and execute and some of them didnt update using the discovery store. I later found out that waydroid is changing the file system to read only.

**Comment by ryanrudolfoba** [comment]
I tried to document my troubleahooting step here -

https://youtu.be/IWe0arEnCRI

TLDR - need to re-run cage command once waydroid exits. Ideally add it to the script but still on testing phase as I can't get consistent results when added to the script.

**Comment by ryanrudolfoba** [comment]
i've updated the script and it seems to have fixed the display environment variable issue.
i cant replicate the issue now - firefox / flatpaks works after exiting waydroid.
