### ISSUE TITLE
New kernel breaks install 

### ISSUE THREAD

**Issue by Pilotej48** [ryanrudolfoba/SteamOS-Waydroid-Installer#108]
New steam is update [
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/174015388/6bb1b4fc-c2ee-485b-b559-df629b3cd911)

**Comment by ryanrudolfoba** [comment]
This will need new kernel modules. I can build one but this will take a while as im traveling.

Or you can build on your own -

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/90
