### ISSUE TITLE
Latest Steam Deck update broke it.

### ISSUE THREAD

**Issue by thanone2** [ryanrudolfoba/SteamOS-Waydroid-Installer#109]
What is says:
"SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65-g1889664e19fc is NOT supported. Exiting immediately."

**Comment by Amras27** [comment]
Same for me :(

**Comment by ryanrudolfoba** [comment]
This will need new kernel modules. I can build one but this will take a while as im traveling.

Or you can build on your own -

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/90

**Comment by thanone2** [comment]
> This will need new kernel modules. I can build one but this will take a while as im traveling.
> 
> Or you can build on your own -
> 
> https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/90

👍
