### ISSUE TITLE
Bluetooth mouse buttons register on screen but nothing

### ISSUE THREAD

**Issue by mikmikmikmik** [ryanrudolfoba/SteamOS-Waydroid-Installer#11]
Bluetooth mouse buttons can be seen registering on screen as being pressed but nothing happens when clicked.
Seems to only be when  I re-plug ext monitor in again to fix the issue in last fault posting.
Have to restart waydroid to get mouse to work again,  but then the mouse won't move to bottom of screen again. 
It looks like I can only use this on the deck display.
Kinda strange that the mouse works perfectly if I press the steam button and wiggle the pointer around in there.

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

Ive been using a plugged in mouse throughout the video and mouse input works.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
