### ISSUE TITLE
Unable to install on SteamOs beta (3.6.8)

### ISSUE THREAD

**Issue by pereiks** [ryanrudolfoba/SteamOS-Waydroid-Installer#111]
Beta channel switched to kernel `6.5.0-valve12-1-neptune-65-g1889664e19fc` which is not supported. Any chance you can add a binder for it?

**Comment by BergaBruh** [comment]
Also didn't support SteamOS Beta 3.7 (kernel `6.5.0-valve13-1-neptune-65-gd5e176bdacb0`)

**Comment by slynobody** [comment]
let a script do the binder-module compilation and updating of your current install: https://github.com/slynobody/SteamOS-Waydroid-Installer

**Comment by ryanrudolfoba** [comment]
PR has been merged that contains binder kernel module for 3.6.8.

Script will now work on latest SteamOS beta / preview.

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/112
