### ISSUE TITLE
How do I build the kernel modules?

### ISSUE THREAD

**Issue by zqpvr** [ryanrudolfoba/SteamOS-Waydroid-Installer#112]
Just give a guide and I can try and build them and maybe do a pr.

**Comment by BergaBruh** [comment]
If you really want it - [how to build kernel (documentation from Arch Wiki)](https://wiki.archlinux.org/title/Kernel/Traditional_compilation), [building kernel with using binder (documentation from Arch Wiki)](https://wiki.archlinux.org/title/Waydroid#Building_a_kernel) and [SteamOS kernel (use needed tags and check commit SHA)](https://gitlab.com/evlaV/linux-integration)

**Comment by slynobody** [comment]
let a script do the binder-module compilation and updating of your current install: https://github.com/slynobody/SteamOS-Waydroid-Installer

**Comment by ryanrudolfoba** [comment]
@zqpvr 

thanks for building it. you would need to do some minor update to the the installer script too -

define the variable for the new kernel (kernel5) -
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/f1473686-7228-437f-af7c-05f0786c632d)

add kernel5 to the logic -
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/d9fb3774-dcfc-4a1d-bfd5-eb3c1a918709)

**Comment by ryanrudolfoba** [comment]
PR merged! Thank you for building it!
