### ISSUE TITLE
Could you patch (or add an option) so that Blue Archive works?

### ISSUE THREAD

**Issue by Emyya** [ryanrudolfoba/SteamOS-Waydroid-Installer#115]
Hello there, not sure if this is the right place but basically an user who goes by "qwerty12356-wart" patched blue archive not long ago on both libhoudini and libndk. (source here: https://github.com/waydroid/waydroid/issues/788#issuecomment-2167334937). The aplication of the patch itself is simple but i tought it would be cool? if this was included by default.

**Comment by ryanrudolfoba** [comment]
Yes i plan to add that to the script. Sometime in August as im on vacation/travelling.

**Comment by ryanrudolfoba** [comment]
duplicate of this -
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/102
