### ISSUE TITLE
New beta update has a new kernel update

### ISSUE THREAD

**Issue by AFreshSalad** [ryanrudolfoba/SteamOS-Waydroid-Installer#116]
`SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65-g1889664e19fc is NOT supported. Exiting immediately.`

Tried to re-run the script with the beta update that includes the Game Recording feature, and it seems like it doesn't install correctly according to this terminal output. Please look into this when you can, thank you!

**Comment by terrorizeikea** [comment]
I am also getting this error. I use the beta for family sharing, would be appreciated if fixed!

**Comment by conmar1001** [comment]
I have kernel 6.5.0-valve13-1neptune-65-gd5e176bdacb0 and it gives same error

**Comment by slynobody** [comment]
> I have kernel 6.5.0-valve13-1neptune-65-gd5e176bdacb0 and it gives same error
This seems to be SteamOS3.7, use https://github.com/slynobody/SteamOS-Waydroid-Installer

**Comment by conmar1001** [comment]
Thank you for that

**Comment by ryanrudolfoba** [comment]
sorry for late reply. i only build for SteamOS Stable / Beta as thats what i use.
the script supports latest Stable and Beta kernel.
