### ISSUE TITLE
Waydroid nukes Display Enviroment Variable when running

### ISSUE THREAD

**Issue by MNarath1** [ryanrudolfoba/SteamOS-Waydroid-Installer#118]
I don't quite understand why but when waydroid runs it will erase the Display env variable and cause programs like Firefox or Flatseal to not be able to run until you restart the Deck in the logs you will get `steamdeck plasmashell[24803]: Error: no DISPLAY environment variable specified`

**Comment by MNarath1** [comment]
i think there is a decky plugin that can run scripts after stopping a game but last time i used it that function worked less than reliable.

**Comment by ryanrudolfoba** [comment]
i've updated the script and it seems to have fixed the display environment variable issue.
i cant replicate the issue now - firefox / flatpaks works after exiting waydroid.
