### ISSUE TITLE
Most probably this is due to python issue.

### ISSUE THREAD

**Issue by ChitandaEur** [ryanrudolfoba/SteamOS-Waydroid-Installer#119]
![88744925-d511-4975-9e23-b756de899ee4](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/117610183/4bde2b57-2693-4a58-80dd-9281d085165c)
Hello! I have tried to install it multiple times, but it keeps prompting "Most probably this is due to a python issue."

**Comment by busybox42** [comment]
If you have sideloaded python with miniconda or brew then this is probably the issue you are having.

**Comment by ChitandaEur** [comment]
> If you have sideloaded python with miniconda or brew then this is probably the issue you are having.如果您已经使用 Miniconda 或 brew 进行侧载 Python，那么这可能是您遇到的问题。
