### ISSUE TITLE
Steam Deck Controls

### ISSUE THREAD

**Issue by jkingsbury1000** [ryanrudolfoba/SteamOS-Waydroid-Installer#12]
Hi,

Not sure if this has been covered? Have installed flawlessley.....however

How do you use the Steam Deck controls to scroll through Android screen menus?

Is there a best configuration?

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
