### ISSUE TITLE
Won't install 

### ISSUE THREAD

**Issue by mc115x** [ryanrudolfoba/SteamOS-Waydroid-Installer#121]
It won't install properly 
![20240708_152132](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/46014890/bc6eabd9-5c50-4de4-8133-36abcee375ea)
![20240708_152132](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/46014890/f09ff231-b21e-46e5-9416-af68d6d05271)

**Comment by ryanrudolfoba** [comment]
thats a python issue. you have 3rd party python installed on your system.
