### ISSUE TITLE
smarttube freezing when launching directly

### ISSUE THREAD

**Issue by powerpuffboysz** [ryanrudolfoba/SteamOS-Waydroid-Installer#122]
So i have smarttube set up to automatically launch from game mode but it freezes when backing out if the video. It works flawlessly when i boot up android_waydroid_cage.sh and then boot the app from the android homescreen

**Comment by ryanrudolfoba** [comment]
script has been updated that fixes this behavior.
please clone the repo to get the latest version and run the install again.
