### ISSUE TITLE
Grab gyroscope and accelerometer data for games that need it?

### ISSUE THREAD

**Issue by AftDawn** [ryanrudolfoba/SteamOS-Waydroid-Installer#123]
Hi, i wanted to play Rotaneo, but the gyro and accelerometer aren't passed through to the game, is there any way of getting this to work (akin to SteamDeckGyroDSU) or is this something that waydroid hasn't added yet?

**Comment by slynobody** [comment]
same question regarding rotation, how could waydroid-sensors be used? (https://github.com/droidian/waydroid-sensors)
