### ISSUE TITLE
when will support of 6.5.0 kernel version added

### ISSUE THREAD

**Issue by Fixnightlol** [ryanrudolfoba/SteamOS-Waydroid-Installer#124]
i cannot install waydroid, because my version of kernel is not supported (sorry for bad english)

**Comment by slynobody** [comment]
open a konsole / terminal: uname -r

if it says '6.5.0-valve13-1-neptune-65-gd5e176bdacb0' then you are on SteamOS 3.7, then go to: https://github.com/slynobody/SteamOS-Waydroid-Installer/tree/main and try that.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. i only build for SteamOS Stable / Beta as thats what i use.
the script supports latest Stable and Beta kernel.
