### ISSUE TITLE
Disable Root

### ISSUE THREAD

**Issue by p1nk13** [ryanrudolfoba/SteamOS-Waydroid-Installer#125]
I'm trying to run some games, but they won't run because they say the device is rooted, is there a way to disable the root?

**Comment by ryanrudolfoba** [comment]
which game? i could give a try.

**Comment by p1nk13** [comment]
While I'm not really having the issue anymore, it still could be a problem.
Cookie Run: Witch's Castle and Cookie Run: Tower of Adventures

**Comment by gagantous** [comment]
> While I'm not really having the issue anymore, it still could be a problem. Cookie Run: Witch's Castle and Cookie Run: Tower of Adventures

hey, i tried to install this game, and i it still said "root detected" how did you resolve this ?

**Comment by p1nk13** [comment]
> Actually waydroid doesn't have root by default, it's just that some apps detect selinux or debugable. you can try [waydroid issue #1060](https://github.com/waydroid/waydroid/issues/1060) or [#935](https://github.com/waydroid/waydroid/issues/935)

Problem with those, can't find either /var/lib/waydroid/waydroid.prop or /var/lib/waydroid/waydroid.cfg

**Comment by gagantous** [comment]
> > This is the default location of the upstream waydroid, maybe @ryanrudolfoba changed it
> 
> No, my bad, you can create them manually. The main thing is to edit the `/var/lib/waydroid/waydroid.cfg` file and then use `sudo waydroid upgrade -o` to update waydroid offline to make it take effect

i have tried that, but it still detected. I play this on my steamdeck

**Comment by gagantous** [comment]
> ```
> ro.adb.secure=1
> ro.debuggable=0
> ro.build.selinux=1
> ```
> 
> these three

I tried this still no luck, maybe its different with steamos (even its archlinux based OS)

**Comment by gagantous** [comment]
@ryanrudolfoba could you test this game ?
i have install it but still no luck so far, it always detected as debugging system

https://github.com/waydroid/waydroid/issues/1060

**Comment by ryanrudolfoba** [comment]
> > This is the default location of the upstream waydroid, maybe @ryanrudolfoba changed it
> 
> No, my bad, you can create them manually. The main thing is to edit the `/var/lib/waydroid/waydroid.cfg` file and then use `sudo waydroid upgrade -o` to update waydroid offline to make it take effect

Dont. The correct way -

Edit /var/lib/waydroid/waydroid_base.prop

Add those three lines and restart waydroid and thats it. Been using this for quite a while now, I haven't added to main script as I dunno if it breaks other things. Maybe I can add a toggle in Waydroid Toolbox to easily change it

**Comment by ryanrudolfoba** [comment]
> @ryanrudolfoba could you test this game ? i have install it but still no luck so far, it always detected as debugging system
> 
> [waydroid/waydroid#1060](https://github.com/waydroid/waydroid/issues/1060)

That game doesn't work for me either even after disable debugging.

**Comment by ryanrudolfoba** [comment]
the waydroid prop options to disable root will be added to newer version of the script
