### ISSUE TITLE
System image hash/python issue? Can’t install

### ISSUE THREAD

**Issue by ZoeyDaKitty** [ryanrudolfoba/SteamOS-Waydroid-Installer#126]
image attached below, I don’t know if I did something wrong? Can’t install at all- included image below

![0619710B-CADE-42C8-B4A6-686343F9A2CE](https://github.com/user-attachments/assets/44d92faa-95a1-4c45-9dba-65928b3505f0)

**Comment by ryanrudolfoba** [comment]
sorry for late reply. the downloaded android image doesnt match the hash - this could be due to a corrupted download from slow internet connection.

run the script again to redownload the android image.
