### ISSUE TITLE
Official Parser for Steam Rom Manager?

### ISSUE THREAD

**Issue by AftDawn** [ryanrudolfoba/SteamOS-Waydroid-Installer#127]
Hi, I use EmuDeck, a part of their system for getting non steam shortcuts into steam is through the use of Steam Rom Manager (SRM), I feel like using SRM to have an easy time getting Android games showing up in game mode would be great in the long term.

**Comment by ryanrudolfoba** [comment]
You can add Android games / apps to Game Mode easily. I've created a guide for it -

https://youtu.be/pkRtPHfa_EM

Steps -

Edit the Game Mode shortcut launch option to inxlude the Android app / game that you want to run automatically.

**Comment by AftDawn** [comment]
And that's great, in the short term. SRM would be a one click setup for game mode, eliminating people from messing up the setup, plus it uses SteamGridDB to fetch images so that game mode doesn't have blank default grids for android games

You could make a simple video on how to setup a SRM parser for Waydroid.

There's even a "manual" parser which will take a folder of .json files to figure out what games are available and how to launch them, cause i have tried setting up a parser but it's hard to get it set up correctly without using manual .json parsing.

The SRM setup it could be as simple as pointing a parser at a subfolder of `Android_Waydroid` (maybe it could be called `SRM entries` or something similar) and naming the parser.

**Comment by ryanrudolfoba** [comment]
sorry not interested in adding this feature at the moment. please feel free to do a PR.

**Comment by AftDawn** [comment]
I got SRM parsing working, don't know how to include the info on it tho, so i'll just leave the config here

```
# Parser type
····Selected: Glob-regex
# Configuration title
····Android Games
# Steam directory
····${steamdirglobal}
# User accounts
····Global
# ROMs directory
····/home/deck/.local/share/applications
# Steam collections
····Android Games
# Executable
····/home/deck/Android_Waydroid/Android_Waydroid_Cage.sh
····[ ]: Follow .lnk or .desktop to destination (Windows and Linux only)
····[ ]: Append arguments to executable
# Command line arguments
····${/(?<=waydroid\.).*/|${fileName}}
# Executable modifier
····"${exePath}"
# "Start In" directory
····
# User's glob
····null
# User's glob-regex
····${/.*waydroid.*\.desktop$/}
# Title modifier
····${/[^.]+(?=\.desktop$)/|${title}}
# Fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Image providers
····Selected: sgdb,steamCDN
# Online image query
····${${finalTitle}}
# Image pool
····${finalTitle}
····[ ]: Local backups (DRM takedown protection)
····[ ]: Allow NSFW artwork
····[ ]: Allow joke artwork
```
