### ISSUE TITLE
Duplicated modprobe command in the script

### ISSUE THREAD

**Issue by karta0807913** [ryanrudolfoba/SteamOS-Waydroid-Installer#128]
hello :D

Thanks for this awesome script!

I realized a duplicate `sudo modprobe binder_linux` is in the script.

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/blob/ee09fe06d72fc0c67e1736fa069e4ba4df535059/steamos-waydroid-installer.sh#L127C35-L127C82

And it's working on my steam deck! Thank you!

**Comment by ryanrudolfoba** [comment]
updated the script to remove the duplicate modprobe command.

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/commit/2593968ffc84dc49b5c8706a2a09918fb453f8f6
