### ISSUE TITLE
Under 20 fps with roblox

### ISSUE THREAD

**Issue by EmiTokisaki** [ryanrudolfoba/SteamOS-Waydroid-Installer#129]
Every game I try to play on Roblox with waydroid is extremely slow. I understand if there's no fix for this but wanted to see if anyone knew of a solution. Putting the graphics on the lowest setting and using gaming mode doesn't seem to help

**Comment by ryanrudolfoba** [comment]
update Roblox make sure you have the latest APK released Aug 01 2024 onwards.

that build allows to have 60FPS -
https://youtu.be/8lDD7mQYEas
