### ISSUE TITLE
Installing Galaxy Store and maybe changing device Model

### ISSUE THREAD

**Issue by Blackwigg** [ryanrudolfoba/SteamOS-Waydroid-Installer#13]
Hi, from every other way that I found on the internet, I only had succes installing waydroid with your video and instructions, since I don't understand linux and programing enought to make things out alone. With that said, I am actually interested in installing Galaxy Store, since Play Store doesn't have good discounts at my contry, but Galaxy Sotre does. I got my hands on the app, but it doesn't work on this setup, guess it's because of the Pixel 5's fingerprint. How could I install this app or change the device model so it would be compatible with galaxy store apps? (I won't pretend to use netflix, so Pixel 5 isn't necesssary).

**Comment by ryanrudolfoba** [comment]
open konsole terminal and type this -

sudo kwrite /var/lib/waydroid/waydroid_base.prop

Kwrite window will open up. Delete this lines -
`##########################################################################
### start of custom build prop - you can safely delete if this causes issue

ro.product.brand=google
ro.product.manufacturer=Google
ro.system.build.product=redfin
ro.product.name=redfin
ro.product.device=redfin
ro.product.model=Pixel 5
ro.system.build.flavor=redfin-user
ro.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.system.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.bootimage.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.display.id=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.build.tags=release-keys
ro.build.description=redfin-user 11 RQ3A.211001.001 eng.electr.20230318.111310 release-keys
ro.vendor.build.fingerprint=google/redfin/redfin:11/RQ3A.211001.001/eng.electr.20230318.111310:user/release-keys
ro.vendor.build.id=RQ3A.211001.001
ro.vendor.build.tags=release-keys
ro.vendor.build.type=user
ro.odm.build.tags=release-keys

### end of custom build prop - you can safely delete if this causes issue
##########################################################################`

Save the file. Restart waydroid.

**Comment by Blackwigg** [comment]
Thanks for the help. I followed your instructions and the terminal said to open the waydroid_base.prop file manually (I used dolphin and went to /var/lib/waydroid/) and save using root permissions and so I did delete the lines as said.

After restarting waydroid the device model wansn't Pixel 5 anymore and the Galaxy Store app didn't crash at open, but after that a message popped saying: "This tablet doesn't support Galaxy Store". Is there any workaround? Maybe it needs a compatible device fingerprint to work?

**Comment by ryanrudolfoba** [comment]
You'd have to find usually a build.prop for a samsung tablet then add it to the waydroid config. I dunno which will be compatible to the galaxy store, so that will be trial and error. XDA will be a good resource for getting a device fingerprint.

**Comment by ryanrudolfoba** [comment]
i've been trying to look for a build.prop for samsung too but the ones i saw are way too old from 10yrs+ ago. if you happen to find a recent one that uses Android 11 please let me know. i'll close this now and feel free to re-open / message me if you get anything.
