### ISSUE TITLE
Waydroid config file missing

### ISSUE THREAD

**Issue by Marcusholoway428** [ryanrudolfoba/SteamOS-Waydroid-Installer#130]
"Errno 104"

**Comment by ryanrudolfoba** [comment]
I've updated the script - please try if you are still getting error.

SteamOS Waydroid Installer script has been updated - this now works with SteamOS 3.6.9.

Install guide - 
https://youtu.be/06T-h-jPVx8

What changed?!?
1. support for SteamOS 3.6.9
2. waydroid bump from 1.4.2 to 1.4.3
3. lxc bump from 0.2 to 0.3
4. binder kernel module re-built using latest May26 commits
5. cleanup the binder kernel folder names so its easier to read
6. remove libndk-fixer (not needed anymore for Roblox)
7. Add sanity check on the waydroid launcher
