### ISSUE TITLE
I get this error when trying to install waydroid

### ISSUE THREAD

**Issue by Axolotl-Gamer** [ryanrudolfoba/SteamOS-Waydroid-Installer#131]
==> Generating pacman master key. This may take some time.
/etc/pacman.d/gnupg/gpg.conf:1: keyword too long
gpg: Generating pacman keyring master key...
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: /etc/pacman.d/gnupg/pubring.gpg: copy to '/etc/pacman.d/gnupg/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing public keyring '/etc/pacman.d/gnupg/pubring.gpg': Invalid packet
gpg: key generation failed: Invalid packet
gpg: Done
==> Updating trust database...
/etc/pacman.d/gnupg/gpg.conf:1: keyword too long
gpg: [don't know]: invalid packet (ctb=00)
gpg: keyring_search failed: Invalid packet
gpg: failed to rebuild keyring cache: Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search failed: Invalid packet
gpg: public key of ultimately trusted key 2A887A25B3B0B495 not found
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_search(first) failed: Invalid packet
gpg: validate_key_list failed
==> ERROR: Trust database could not be updated.

**Comment by ryanrudolfoba** [comment]
what SteamOS version are you on?
are you on Stable or Beta version?

**Comment by ryanrudolfoba** [comment]
script is failing on -
sudo pacman-key --init
sudo pacman-key --populate

This is a pacman SteamOS issue.
