### ISSUE TITLE
no me deja actualizar waydrioid con el scrip despues de haver actualizado SteamOs

### ISSUE THREAD

**Issue by MRcabalapsa** [ryanrudolfoba/SteamOS-Waydroid-Installer#132]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65-g1889664e19fc is NOT supported. Exiting immediately.

esto me sale estoy en la version de steamos en la que se puede usar la familia de steam

**Comment by MRcabalapsa** [comment]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65-g1889664e19fc is NOT supported. Exiting immediately.

**Comment by ryanrudolfoba** [comment]
your screenshot / error message means you are using an older version of the script.
clone the repo again to get the latest version and run the install.
