### ISSUE TITLE
A question about waydroid_script and microG

### ISSUE THREAD

**Issue by Tykveg** [ryanrudolfoba/SteamOS-Waydroid-Installer#133]
Can I use stock [waydroid_script](https://github.com/casualsnek/waydroid_script) to install stuff? Because I want to install microG but I'm not sure how to do that outside of using waydroid_script as it is. I am aware, that this script includes libndk, so I don't need to use waydroid_script to install that. I only want to install microG (and probably Widevine DRM).

**Comment by ryanrudolfoba** [comment]
this already includes libndk, widevine and gapps.

If you want microG you will need to edit the script. Should be fairly easy juat let me know if thats what you want.

**Comment by ryanrudolfoba** [comment]
Edit the script as follows -

on line 275 remove `-s GAPPS` -
![image](https://github.com/user-attachments/assets/62cdfb36-ffa1-4d8d-a42f-e4ee6721cbb1)

on line 302 add microg -
![image](https://github.com/user-attachments/assets/3563e7e3-c6f8-4531-9ad8-fd47db14f73d)


and thats it. save the file and run the script. it will install microg instead.

**Comment by Tykveg** [comment]
> Edit the script as follows -
> 
> on line 275 remove `-s GAPPS` - ![image](https://private-user-images.githubusercontent.com/98122529/355568333-62cdfb36-ffa1-4d8d-a42f-e4ee6721cbb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzA4MzQsIm5iZiI6MTcyMjk3MDUzNCwicGF0aCI6Ii85ODEyMjUyOS8zNTU1NjgzMzMtNjJjZGZiMzYtZmZhMS00ZDhkLWE0MmYtZTRlZTY3MjFjYmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzJjN2QzZTcwN2EyMzk5Y2FhODZkYWE1NTBiMmZmYTJmOWM0MGYzMGZiZWMwYTBhZGZjNjNlODFlNzFmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCncCUo747iqdOZp3F3OZGwcMsOdsdAJetZdpQXBWOc)
> 
> on line 302 add microg - ![image](https://private-user-images.githubusercontent.com/98122529/355568549-3563e7e3-c6f8-4531-9ad8-fd47db14f73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzA4MzQsIm5iZiI6MTcyMjk3MDUzNCwicGF0aCI6Ii85ODEyMjUyOS8zNTU1Njg1NDktMzU2M2U3ZTMtYzZmOC00NTMxLTlhZDgtZmQ0N2RiMTRmNzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOGVjZjNmMzI4ZDEzYWVmNTVhNmEwNzExYjE5NTkwZTY4MzNmMmUzNDcwOGUzYWRkOTA4MTJiMTEyZGRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gagAzQXmATy0AjhhrQanYBnnBOwyYiGulkkghCv5jXM)
> 
> and thats it. save the file and run the script. it will install microg instead.
> 
> and yes this uses waydroid_script from casualsnek!

Oh, that is simple. I will try fresh install.

**Comment by Tykveg** [comment]
> > Edit the script as follows -
> > on line 275 remove `-s GAPPS` - ![image](https://private-user-images.githubusercontent.com/98122529/355568333-62cdfb36-ffa1-4d8d-a42f-e4ee6721cbb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzA4MzQsIm5iZiI6MTcyMjk3MDUzNCwicGF0aCI6Ii85ODEyMjUyOS8zNTU1NjgzMzMtNjJjZGZiMzYtZmZhMS00ZDhkLWE0MmYtZTRlZTY3MjFjYmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzJjN2QzZTcwN2EyMzk5Y2FhODZkYWE1NTBiMmZmYTJmOWM0MGYzMGZiZWMwYTBhZGZjNjNlODFlNzFmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCncCUo747iqdOZp3F3OZGwcMsOdsdAJetZdpQXBWOc)
> > on line 302 add microg - ![image](https://private-user-images.githubusercontent.com/98122529/355568549-3563e7e3-c6f8-4531-9ad8-fd47db14f73d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzA4MzQsIm5iZiI6MTcyMjk3MDUzNCwicGF0aCI6Ii85ODEyMjUyOS8zNTU1Njg1NDktMzU2M2U3ZTMtYzZmOC00NTMxLTlhZDgtZmQ0N2RiMTRmNzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjOGVjZjNmMzI4ZDEzYWVmNTVhNmEwNzExYjE5NTkwZTY4MzNmMmUzNDcwOGUzYWRkOTA4MTJiMTEyZGRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gagAzQXmATy0AjhhrQanYBnnBOwyYiGulkkghCv5jXM)
> > and thats it. save the file and run the script. it will install microg instead.
> > and yes this uses waydroid_script from casualsnek!
> 
> Oh, that is simple. I will try to do a fresh install.

Sorry for the late reply. Yes, everything worked, thank you so much! Aurora store is currently has some issues on waydroid, but it's unrelated. I think it will be cool to have microG install as a script argument.
