### ISSUE TITLE
Suggestion: Make Google Apps Optional

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#135]
I would suggest trying to court steamOS to include Waydroid by default, as such they may not want to promote the Google Play store as that may be sean as a direct competitor to steam. I could definitely see the Steam webstore eventually expanding into Android Games.

**Comment by slynobody** [comment]
second that. if there will be a steam appstore, it should not only implement games but supply all other (free) apps, too. i would rather trust valve than google. and you would have an alternative to the google-monopoly (see eu-legislation f.e.)

**Comment by ryanrudolfoba** [comment]
simple menu to have the user choose if with GAPPS or NO GAPPS.
![image](https://github.com/user-attachments/assets/03a90a0c-3129-4a0c-b94b-c289f4c5618b)

this will be added on the next version.
