### ISSUE TITLE
Suggestion: Disable Initial Device Setup via ADB 

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#136]
Because Wifi is not detected the Intial Device Setup Notice will constantly appear in the Notification bar

**Comment by ryanrudolfoba** [comment]
which ADB command? we can add this using the command -

sudo waydroid shell `command etc etc`

**Comment by DanielLester83** [comment]
Try sudo waydroid shell pm disable com.google.android.setupwizard

This might break things on a fresh install, needs testing.

**Comment by ryanrudolfoba** [comment]
added to script and doesnt seem to cause any issues. this will be incluided in the next version.
