### ISSUE TITLE
6.5.0-valve16-1-neptune-65-gc9ad4106624e is NOT supported

### ISSUE THREAD

**Issue by TirpitzPlayer** [ryanrudolfoba/SteamOS-Waydroid-Installer#138]
During attempt of installation I got this error message:
`6.5.0-valve16-1-neptune-65-gc9ad4106624e is NOT supported`

**Comment by slynobody** [comment]
until this repo gets updated, clone this: https://github.com/slynobody/SteamOS-Waydroid-Installer ('3_6_kernel_module_build.sh', then 'steamos-waydroid-installer.sh', if you lost net after the update then also: 'netrestore.sh')

**Comment by ryanrudolfoba** [comment]
SteamOS Waydroid Installer script has been updated - this now works with SteamOS 3.6.9.

Install guide - 
https://youtu.be/06T-h-jPVx8

What changed?!?
1. support for SteamOS 3.6.9
2. waydroid bump from 1.4.2 to 1.4.3
3. lxc bump from 0.2 to 0.3
4. binder kernel module re-built using latest May26 commits
5. cleanup the binder kernel folder names so its easier to read
6. remove libndk-fixer (not needed anymore for Roblox)
7. Add sanity check on the waydroid launcher
