### ISSUE TITLE
Native Multitouch Support

### ISSUE THREAD

**Issue by osirase** [ryanrudolfoba/SteamOS-Waydroid-Installer#14]
Like as demonstrated in this video: https://youtu.be/v3BTESxhMMg?si=awPEoabG5HTLA_C4

**Comment by ryanrudolfoba** [comment]
i'm rewriting my script so it doesnt pull up packages from the pacman repo. will take a look into this while i rewrite it.

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
