### ISSUE TITLE
Individual Start Menu Shortcuts Don't Work In Desktop Mode

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#142]
It trys to open the closes before a window opens.
Also, when I try run the command in konsole I get:

Starting waydroid session
WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

I suspect you need to expose /run/user/1000/gamescope-0 (which runs xwayland) to the container.

Then I think use waydroid prop set WAYLAND_DISPLAY gamescope-0.

However, There's a good chance that the real solution is more complicated.

**Comment by ryanrudolfoba** [comment]
clome the repo to get the latest version and install it.

Run ./Android_Waydroid_Cage.sh name_of_android_app
