### ISSUE TITLE
Individual Start Menu Shortcuts Can Work In Desktop Mode

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#144]
I figured out how to make the shortcuts work.

1. Make a script at /home/deck/Android_Waydroid/Wrapper/waydroid
`#!/bin/bash

if [ $1 = "app" ] && [ $2 = "launch" ]
then
  /home/deck/Android_Waydroid/Android_Waydroid_Cage.sh $3
else
  /usr/bin/waydroid "$@"
fi`

2. chmod +x /home/deck/Android_Waydroid/Wrapper/waydroid

3. make a path changer as root at /etc/profile.d/Waydroid.sh
`#!/bin/sh

export PATH="/home/deck/Android_Waydroid/Wrapper/:$PATH"`

4. restart all shells/reboot

Some issues are that all lock screens and launch on startup apps will still open first if any are enabled.

An odd sound plays when it boots, possible hardware initialization.

Also the notification pull down appears at launch

**Comment by ryanrudolfoba** [comment]
I would just use ~/Android_Waydroid/Android_Waydroid_Cage.sh `name of android app` as that contains the startup scripts for controller detection etc etc

**Comment by ryanrudolfoba** [comment]
updated the README to reflect this info

**Comment by CoderMonkey1956** [comment]
> I figured out how to make the shortcuts work.
> 
> 1. Make a script at /home/deck/Android_Waydroid/Wrapper/waydroid
>    `#!/bin/bash
> 
> if [ $1 = "app" ] && [ $2 = "launch" ] then /home/deck/Android_Waydroid/Android_Waydroid_Cage.sh $3 else /usr/bin/waydroid "$@" fi`
> 
> 2. chmod +x /home/deck/Android_Waydroid/Wrapper/waydroid
> 3. make a path changer as root at /etc/profile.d/Waydroid.sh
>    `#!/bin/sh
> 
> export PATH="/home/deck/Android_Waydroid/Wrapper/:$PATH"`
> 
> 4. restart all shells/reboot
> 
> Some issues are that all lock screens and launch on startup apps will still open first if any are enabled.
> 
> An odd sound plays when it boots, possible hardware initialization.
> 
> Also the notification pull down appears at launch

I think you meant to format it like this? Correct me if I'm wrong though

1. Make a script at /home/deck/Android_Waydroid/Wrapper/waydroid
```#!/bin/bash
if [ $1 = "app" ] && [ $2 = "launch" ]
then
/home/deck/Android_Waydroid/Android_Waydroid_Cage.sh $3
else
/usr/bin/waydroid "$@"
fi```

2. chmod +x /home/deck/Android_Waydroid/Wrapper/waydroid

3. make a path changer as root at /etc/profile.d/Waydroid.sh
```#!/bin/sh

export PATH="/home/deck/Android_Waydroid/Wrapper/:$PATH"```

4. restart all shells/reboot

**Comment by DanielLester83** [comment]
Yeah, at a glance that looks better formatted than the original post

**Comment by CoderMonkey1956** [comment]
> Yeah, at a glance that looks better formatted than the original post

Just noticed I messed it up AGAIN lol, GitHub formatting is crazy.

**Comment by felipecrs** [comment]
I would recommend this improvement to the script:

```bash
#!/bin/sh

if [ $1 = "app" ] && [ $2 = "launch" ]; then
    shift 2
    exec "$HOME/Android_Waydroid/Android_Waydroid_Cage.sh" "$@"
else
    exec /usr/bin/waydroid "$@"
fi
```
