### ISSUE TITLE
How To Rotate the Screen

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#145]
You can rotate the screen by wrapping the launch commands like this. although there may be a better system such as mapping the steam deck gyro to hotkeys that would automatically rotate. Note that rotating does not change the orientation of the touch pad mouse.

/usr/bin/kscreen-doctor output.eDP.rotation.normal; waydroid app launch com.chess ; /usr/bin/kscreen-doctor output.eDP.rotation.right @@

**Comment by ryanrudolfoba** [comment]
the way i handle it is via waydroid prop options. its messy thats why i didnt add it to the main script yet. cant find the actual config file that waydroid prop edits / reads so it will be easier if i can modify that file directly.

here is a demo touch input is also rotated -

https://youtu.be/XEcIYBDoOZk

**Comment by DanielLester83** [comment]
> kscreen-doctor doesnt seem to work in gamescope / Game Mode. works fine on X11 Desktop Mode.
> 
> the way i handle it is via waydroid prop options. its messy thats why i didnt add it to the main script yet. cant find the actual config file that waydroid prop edits / reads so it will be easier if i can modify that file directly.
> 
> here is a demo touch input is also rotated -
> 
> https://youtu.be/XEcIYBDoOZk

I think it's modifying the /system/build.prop file inside of the Android OS. see: https://source.android.com/docs/core/architecture/configuration

**Comment by ryanrudolfoba** [comment]
the current workflow is this -

1. Launch Android shortcut
2. Ask user - portrait or landscape?
3. Run waydroid, wait a few seconds, set the prop options to either portrait / landscape based on user choice, exit waydroid
4. Run waydroid again and it will now launch either portrait / landscape based on user choice

I want to eliminate step3 as it adds a bit of delay. Unfortunately the waydroid prop set command only works when waydroid is running. If anyone knows what file to edit that is the equivalent of `waydroid prop set persist.waydroid.width` and `waydroid prop set persist.waydroid.height` please let me know.

**Comment by DanielLester83** [comment]
You might experiment wlr-randr --output X11-1 --custom-mode 800x1280@60Hz --transform 90 ;

Ideally, we need a android app that could receive signals from a SteamDeckGyroDSU server and force rotation by actual rotation or something similar.

**Comment by ryanrudolfoba** [comment]
Yes thats what ive been using - wlr-randr.

I'll upload a separate Android Waydroid Launcher that contains rotation

**Comment by DanielLester83** [comment]
> > kscreen-doctor doesnt seem to work in gamescope / Game Mode. works fine on X11 Desktop Mode.
> > the way i handle it is via waydroid prop options. its messy thats why i didnt add it to the main script yet. cant find the actual config file that waydroid prop edits / reads so it will be easier if i can modify that file directly.
> > here is a demo touch input is also rotated -
> > https://youtu.be/XEcIYBDoOZk
> 
> I think it's modifying the /system/build.prop file inside of the Android OS. see: https://source.android.com/docs/core/architecture/configuration

I think the /system/build.prop file is inside a zipped img file located at ~/waydroid/images/system.img
I would suggest making a modified copy of that image file during the install and swapping the names around before the waydroid service starts.

**Comment by ryanrudolfoba** [comment]
clone the repo or get the Android_Waydroid_Cage-experimental.sh from the extras folder.
add to Steam and let me know how it goes.

**Comment by ryanrudolfoba** [comment]
Experimental launcher in action showing Waydroid rotation -

https://youtu.be/OxApPDhZn9I

**Comment by ryanrudolfoba** [comment]
screen rotation added. clone the repo to get the latest version, and manually add the exprimental launcher in Game Mode.
