### ISSUE TITLE
Suggestion: Add Icon Art

### ISSUE THREAD

**Issue by DanielLester83** [ryanrudolfoba/SteamOS-Waydroid-Installer#146]
Steam has recently increased the size limits see: https://partner.steamgames.com/doc/store/assets

I think the procedure would be:

create the images with the same base name and copy the images here: /home/deck/.steam/steam/userdata/ User ID /config/grid/

modify /home/deck/.steam/steam/userdata/ User ID /config/shortcuts.vdf to add the icon path
see: https://developer.valvesoftware.com/wiki/Add_Non-Steam_Game

**Comment by slynobody** [comment]
what is your thought: how could the script get the Steam-UserID? How can one set all the different form of icons for desktop-mode (if i remember it right there are 4)?

**Comment by DanielLester83** [comment]
To get the userid(s) on the steam deck run `ls  -d /home/deck/.steam/userdata/*/ | xargs -n 1 basename`.
There's probably going to be only 1 userid and I doubt there would be any harm in just copying the images to every folder such as `cp * home/deck/.steam/steam/userdata/*/config/grid/`

You get or set the appid by either reading or modifying shorcuts.vdf
see: https://developer.valvesoftware.com/wiki/Steam_Library_Shortcuts

make a 512px x 512px bitmap file named <appid>-icon.ico
make a 600px x 900px png Library Capsule named <appid>p.png
make a 3840px x 1240px png Library Hero named <appid>_hero.png
make a 1280px x 720px png Library Logo named <appid>_logo.png 
make a 920px x 430px png Library Header named <appid>.png

have the script copy these images to home/deck/.steam/steam/userdata/<userid> /config/grid/`

The "Current Templates" link at https://partner.steamgames.com/doc/store/assets links to a dropbox account with template psd files.

**Comment by slynobody** [comment]
thank you! great and compact info. how would you change then lines 392/395 in the installer with (nice looking) art?

**Comment by DanielLester83** [comment]
> thank you! great and compact info. how would you change then lines 392/395 in the installer with (nice looking) art?

Unfortunately, it's too complicated for me to make a simple bash script change, because shortcuts.vdf contains unsigned 32 bit number values as well as some as unicode? text . A better progrmmer tham me would be best to use one of the programs listed here:
https://developer.valvesoftware.com/wiki/KeyValues

The install files could be named anything like waydroid_header.png and the script should rename them later.

**Comment by ryanrudolfoba** [comment]
Haven't checked but if its too complicated I think easiest will be to bundle icon art, copy it to ~/Android_Waydroid and add instructions to use those icon art to customize the launcher.

**Comment by ryanrudolfoba** [comment]
this is too complicated for me. feel free to do a PR instead.
