### ISSUE TITLE
Sonolus crashing

### ISSUE THREAD

**Issue by Roctivels** [ryanrudolfoba/SteamOS-Waydroid-Installer#147]
So Sonolus works fine in the main menu and everything, but after you add a custom server (i tried three different servers i think) it lags, freezes and closes the game without an error message or warning, tried reinstalling, changing settings in sonolus, nothing worked.

**Comment by ryanrudolfoba** [comment]
Unfortunately I can't get it to work either. Not an issue with the script - could be an issue with waydroid compatibility, or the app itself.

I would suggest another rhythm game - Cytoid and Hatsune Miku.
Make sure to configure Waydroid Toolbox to lower the audio latency for rhythm games.
