### ISSUE TITLE
PUBG Mobile crashes during launch

### ISSUE THREAD

**Issue by vradinolfi** [ryanrudolfoba/SteamOS-Waydroid-Installer#15]
Set up went smooth but I can’t get PUBG to run - I thought arm translation was in so I thought it would work but it crashes during the loading screen after downloading resources. Any one have any luck?

**Comment by ryanrudolfoba** [comment]
arm translation is included - if its not included PUBG wont show up in Playstore at all.

Could be isolated game compatibility issue with waydroid. Could be fixed on future waydroid versions. I'll update the script when a new waydroid version is available.
