### ISSUE TITLE
Bug installing

### ISSUE THREAD

**Issue by bigkeegs** [ryanrudolfoba/SteamOS-Waydroid-Installer#152]
I can see what's going on and can fix it, but I share it here incase you wanted to optimise it:

SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
**error: config file /etc/pacman.conf, line 42: invalid value for 'SigLevel' : 'addRequired'
error parsing '/etc/pacman.conf'
mkdir: cannot create directory ‘’: No such file or directory
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
chmod: cannot access '/trustdb.gpg': No such file or directory
error: config file /etc/pacman.conf, line 42: invalid value for 'SigLevel' : 'addRequired'
error parsing '/etc/pacman.conf'
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
Error initializing keyring! Run the script again to install waydroid.**
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

$ uname -r
6.1.52-valve16-1-neptune-61

**Comment by ryanrudolfoba** [comment]
Based on the error thats a pacman issue.  I havent encountered that error yet.
Please share steps how to fix it, i'll see if i can add it to the script. thank you.

**Comment by ryanrudolfoba** [comment]
feel free to update with the solution and i'll see if i can add it to the script.

**Comment by bigkeegs** [comment]
The error was mine. My pacman.conf was messed up. Sorry about that, my mistake.
