### ISSUE TITLE
Config File missing along with directory errors

### ISSUE THREAD

**Issue by GingerBobRoss** [ryanrudolfoba/SteamOS-Waydroid-Installer#157]
Operating System: SteamOS 3.5.19
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.9
Kernel Version: 6.1.52-valve16-1-neptune-61 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 11.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

I am trying to install WayDroid on the latest stable release and I am running into errors during the install. Waydroid will still run, but I am not able to run the certified script and i do not have any applications.

During the install; the installer reports:
`Config file missing. Lets configure waydroid.` and it proceeds to download the images.
Shortly after downloading Gapps; i get Shell-init errors: `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or `directory.`

I have uninstalled and removed all files and reinstalled about 3 times, but get the same errors

**Comment by 1ming** [comment]
I think i saw the same error, my full console output is at the bottom.

In my case, it looks like the shortcuts creation fail due to unsupported file type:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Unsupported file type
```
I tried running this command manually: `steamos-add-to-steam /home/deck/Android_Waydroid/Android_Waydroid_Cage.sh` and saw the same error: `Unsupporte dfile type`.
Based on this reddit post, it sounds like there was a change from steamOS a few months ago that makes this only support `.exe` and `.dll` or something like that? https://www.reddit.com/r/SteamDeck/comments/1cpv8q4/adding_games_to_steam/

Anyway, in the meantime, my workaround was going to steam and manually adding the two shortcuts as "non-steam games" directly from the Steam application: `/home/deck/Android_Waydroid/Android_Waydroid_Cage.sh`,  and `/usr/bin/steamos-nested-desktop`.

```
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve12-1-neptune-65 is supported. Proceed to next step.
Please enter current sudo password:
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-11-09
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
Binder kernel module has been installed!
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
[09:56:23] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240928-GAPPS-waydroid_x86_64-system.zip/download
[Downloading] 877.79 MB/877.88 MB    26330.82 kbps(approx.)[09:56:49] Validating system image
[09:56:50] Extracting to /var/lib/waydroid/images
[09:57:01] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240928-MAINLINE-waydroid_x86_64-vendor.zip/download
[Downloading] 181.67 MB/181.82 MB    32167.15 kbps(approx.)[09:57:08] Validating vendor image
[09:57:08] Extracting to /var/lib/waydroid/images
 Waydroid initialization completed without errors!
INFO: Downloading libndktranslation.zip now to /home/deck/.cache/waydroid-script/downloads/libndktranslation.zip .....
INFO: Extracting /home/deck/.cache/waydroid-script/downloads/libndktranslation.zip to /tmp/libndkunpack
INFO: Copying libndk library files ...
INFO: libndk installation finished
INFO: Downloading widevine.zip now to /home/deck/.cache/waydroid-script/downloads/widevine.zip .....
INFO: Extracting /home/deck/.cache/waydroid-script/downloads/widevine.zip to /tmp/widevineunpack
INFO: Copying widevine library files ...
INFO: widevine installation finished
Casualsnek script done.
Adding shortcuts to game mode. Please wait.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Unsupported file type
Android_Waydroid_Cage.sh shortcut has been added to game mode.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Unsupported file type
steamos-nested-desktop shortcut has been added to game mode.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Waydroid has been successfully installed!
```

**Comment by ryanrudolfoba** [comment]
I should have worded the script status messages - `Config file missing` means it detected that its a fresh install and will trigger to download the waydroid images and generate a new config file.

The other errors are Steam warnings - afaik this are cosmetics. I'll see if i can filter those out

**Comment by 1ming** [comment]
Yeah I think the only real issue for me was just the shortcuts didn't get added: I couldn't find `Android_Waydroid_Cage.sh` in my steam library when I went back to gaming mode. Everything else seems fine.

**Comment by ryanrudolfoba** [comment]
This now supports latest SteamOS beta 3.6.16 / 3.6.17.
clone the repo to get the latest version.

i've also updated the script to have additional sanity checks and trimmed the output of steamos-add-to-steam.

**Comment by ryanrudolfoba** [comment]
if you need further help please feel free to update this issue.
