### ISSUE TITLE
Unable to install Waydroid due to unsupported Kernel

### ISSUE THREAD

**Issue by d3vC0mm4nd3rShadowSlayer29** [ryanrudolfoba/SteamOS-Waydroid-Installer#160]
Here's the output from the Terminal:

SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve19-1-neptune-65 is NOT supported. Exiting immediately.

::: Details of my SteamDeck :::
Operating System Version:
"SteamOS Holo" (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.0-valve19-1-neptune-65-g8e4b171a9b33
X Server Vendor: The X.Org Foundation
X Server Release: 12101011
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240806.97925

Steam Beta Branch:  Steam Deck Beta:
Steam Version:  1725654351
Steam Client Build Date:  Sat, Sep 7 04:08 UTC -08:00
Steam Web Build Date:  Sat, Sep 7 04:07 UTC -08:00
Steam API Version:  SteamClient021

**Comment by ryanrudolfoba** [comment]
Script updated to support SteamOS 3.6.2. please clone the repo to get the latest version.

![image](https://github.com/user-attachments/assets/a5a3ea57-42ac-46d9-ab46-45b4a88b347c)
