### ISSUE TITLE
Cant install on SD Oled 1tb

### ISSUE THREAD

**Issue by sobir8** [ryanrudolfoba/SteamOS-Waydroid-Installer#161]
error as below

6.5.0-valve19-1-neptune-65 is NOT supported. Exiting immediately.

**Comment by ryanrudolfoba** [comment]
Make sure you have latest version of the script.

Clone the repo to get latest version and run the install again.

**Comment by ryanrudolfoba** [comment]
This now supports latest SteamOS beta 3.6.16 / 3.6.17.
clone the repo to get the latest version.
