### ISSUE TITLE
Error installing binder kernel module

### ISSUE THREAD

**Issue by ghost** [ryanrudolfoba/SteamOS-Waydroid-Installer#163]
Operating System: SteamOS 3.6.13 Build: 20240913.113
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.5.0-valve19-1-neptune-65-g8e4b171a9b33 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve19-1-neptune-65 is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-11-09
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
cp: cannot create regular file '/lib/modules/6.5.0-valve19-1-neptune-65-g8e4b171a9b33/binder_linux.ko.zst': Read-only file system
Error installing binder kernel module. Run the script again to install waydroid.
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

I'm on the latest beta update and have tried re-running the script.

**Comment by GhostDragon5745** [comment]
I have the same issue. Since it seems to get stuck on the read only file system, perhaps it could be installed to a system extension image instead? I followed a guide for installing Tailscale like that and it seems to neatly sidestep the readonly thing, though I am unsure how (or if) it could be applied in this case.

**Comment by ryanrudolfoba** [comment]
This now supports latest SteamOS beta 3.6.16 / 3.6.17.
clone the repo to get the latest version.

i've also added sanity checks and verbose messages to see where it is failing / getting stuck.

**Comment by ryanrudolfoba** [comment]
sorry for late reply. I just tried this on a fresh SteamOS 3.5.19 install and it works OK.

maybe the git clone command some files were not cloned completely. 

go to the binder folder > 6.1.52-valve16-1-neptune-61

check that there is a file there called binder_linux.ko.zst

**Comment by ryanrudolfoba** [comment]
havent heard back, feel free to update this if further help is needed.

im also will be updating the script to support the latest SteamOS 3.6.19 stable.
