### ISSUE TITLE
Having issues receiving network requests?

### ISSUE THREAD

**Issue by ktsuttlemyre** [ryanrudolfoba/SteamOS-Waydroid-Installer#164]
First off, thanks very much for this work. 
Secondly, I want to send videos and/or remote control the android session from my phone 

I'm trying to use 
https://play.google.com/store/apps/details?id=com.softmedia.receiver.castapp
And
https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp
And they both seem to have trouble accepting incoming requests from the network.

Is there a way to upgrade the network access level to host or some other network configuration that is impeding incoming requests to the container?

**Comment by ryanrudolfoba** [comment]
this might need bridge network config -

https://github.com/supechicken/waydroid-androidtv-build/issues/6#issuecomment-2381449203

**Comment by ryanrudolfoba** [comment]
after some testing - making a bridge is not possible as Steam Deck doesnt have an ethernet interface.

**Comment by Deadboy666** [comment]
ip addr to check network interfaces
the ethernet is only exposed when docked to one
maybe target wlan0 for the bridge when using wifi

**Comment by ryanrudolfoba** [comment]
> ![Image](https://github.com/user-attachments/assets/7dcc17c4-c5e3-4834-a7c5-a1fc0c631468)
> 
> ![Image](https://github.com/user-attachments/assets/b6dfb64f-2320-45bb-bb23-b380ac723258)
> 
> it works
> 
> Ethernet:
> 
> nmcli connection add type bridge ifname br0 stp no nmcli connection add type bridge-slave ifname enp4s0f3u1u4c2 master br0 nmcli connection up bridge-br0 nmcli connection up bridge-slave-enp4s0f3u1u4c2 sudo nmcli connection add type ethernet slave-type bridge autoconnect yes con-name waylanbr0-slave ifname enp4s0f3u1u4c2 master waylanbr0
> 
> wifi:
> 
> nmcli connection add type bridge ifname br0 stp no nmcli connection add type bridge-slave ifname wlan0 master br0 nmcli connection up bridge-br0 nmcli connection up bridge-slave-wlan0 sudo nmcli connection add type ethernet slave-type bridge autoconnect yes con-name waylanbr0-slave ifname wlan0 master waylanbr0

I'll give this a shot thank you!

**Comment by Deadboy666** [comment]
ip addr is how i found the interfaces
