### ISSUE TITLE
Missing dbus module error (default python install)

### ISSUE THREAD

**Issue by plyfrm** [ryanrudolfoba/SteamOS-Waydroid-Installer#165]
```
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly
Most probably this is due to python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.3
Something went wrong! Performing cleanup. Run the script again to install waydroid.
```
As you can see, this is running the default python install and not a third party one like in the previous issues with a similar error.
I tried running the `import dbus.mainloop.glib` line in the python repl, both under root and under the deck user and it worked both times, so I'm pretty confused by this.

**Comment by ryanrudolfoba** [comment]
What SteamOS version is this?

**Comment by plyfrm** [comment]
Latest stable version (3.5.19)

**Comment by plyfrm** [comment]
Small update on this: `python` and `python3` were pointing to different executables, ended up with a python version from homebrew somehow, which `python3` was pointing to. Uninstalling that version fixed the issue and the rest of the installation went smoothly.
