### ISSUE TITLE
Sucessful script run, but unable to actually install, multiple attempts across 2 different factory resets of deck.

### ISSUE THREAD

**Issue by dilydaly** [ryanrudolfoba/SteamOS-Waydroid-Installer#166]
Steamdeck with all games and emulators -> clone Repo -> asks for sudo pass and fails even when supplied with correct pass until I run scripts with sudo -> Run script(s) -> scripts complete but no "Android_Waydroid" file in home folder, and shortcuts don't install with similar issues as in [this other issue](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/157), unable to manually add caged-waydroid since the location in the script "Android_Waydroid" does not exist for me to add to non-steam game.

===================================================================================

Factory Reset Steamdeck in gaming mode settings - > set user password using user account GUI as according to video -> clone repo -> run installer -> script still asks to set sudo pass and fails itself after setting pass and refusing to accept the pass that was just entered. -> run script with sudo, it works and accepts pass. 

Same as previous attempt, script runs but no "Android_Waydroid" folder made, nor any shorcuts added to game mode.
If I check the taskbar GUI menu, I can see waydroid added at the bottom of the programs list.

===================================================================================

Factory Reset Steamdeck again -> password set using "passwd" command -> steamos-readonly disable -> clone repo -> scripts refuse to recognize sudo pass being set already, supply the same pass that is already set -> script fails even when entering the correct sudo pass-> run script with sudo, script completes, but same as before, no new folders, no new shortcuts.

Konsole output  following "sudo ./steamos-waydroid-installer.sh":

```SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Error cloning Casualsnek repo! Trying to clone again using backup repo.
Casualsnek repo has been successfully cloned!
Warning: The rootfs is already read-write!
Nothing is performed.
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/464FDEED96F0EA31BF538140E1736618CFBFDF93.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Locally signing trusted keys in keyring...
-> Locally signed 10 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
-> Disabled 33 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  10  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  10  signed:  77  trust: 0-, 0q, 0n, 10m, 0f, 0u
gpg: depth: 2  valid:  55  signed:  22  trust: 55-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-11-09
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
Binder kernel module has been installed!
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
[17:24:57] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20241005-GAPPS-waydroid_x86_64-system.zip/download
[Downloading] 877.79 MB/877.88 MB    51953.38 kbps(approx.)[17:25:12] Validating system image
[17:25:12] Extracting to /var/lib/waydroid/images
[17:25:22] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20241005-MAINLINE-waydroid_x86_64-vendor.zip/download
[Downloading] 181.53 MB/181.83 MB    50949.31 kbps(approx.)[17:25:30] Validating vendor image
[17:25:30] Extracting to /var/lib/waydroid/images
Waydroid initialization completed without errors!
INFO: Downloading libndktranslation.zip now to /home/root/.cache/waydroid-script/downloads/libndktranslation.zip .....
14.4MiB [00:01, 8.99MiB/s]
INFO: Extracting /home/root/.cache/waydroid-script/downloads/libndktranslation.zip to /tmp/libndkunpack
INFO: Copying libndk library files ...
INFO: libndk installation finished
INFO: Downloading widevine.zip now to /home/root/.cache/waydroid-script/downloads/widevine.zip .....
3.94MiB [00:00, 11.9MiB/s]
INFO: Extracting /home/root/.cache/waydroid-script/downloads/widevine.zip to /tmp/widevineunpack
INFO: Copying widevine library files ...
INFO: widevine installation finished
Casualsnek script done.
Adding shortcuts to game mode. Please wait.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Usage: steamos-add-to-steam [-ui] <path>
Android_Waydroid_Cage.sh shortcut has been added to game mode.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Unsupported file type
steamos-nested-desktop shortcut has been added to game mode.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Waydroid has been successfully installed!
(deck@steamdeck SteamOS-Waydroid-Installer)$ 
```

**Comment by ryanrudolfoba** [comment]
ive updated the script. please clone the repo again and check if it fixes your issues.

**Comment by dilydaly** [comment]
Formatted Deck Again.

New storage checks messages appear, otherwise behaviour is the same. Script does not function correctly for me without sudo.

Once sudo is applied, the script runs its way through with the same behaviour as before. Adds a Waydroid entry in my start menu at the bottom. Does not generate any shortcuts.  Rerunning the script with sudo after install states that everything needed is already installed. Uninstalls also need sudo in the extras folder.

```SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Checking if home partition has enough free space
home partition has 252682336 free space.
home partition has enough free space.
Checking if var partition has enough free space
var partition has 150138 free space.
var partition has enough free space.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is wrong! Re-run the script and make sure to enter the correct sudo password!
(deck@steamdeck SteamOS-Waydroid-Installer)$ 
```

**Comment by ryanrudolfoba** [comment]
> Script does not function correctly for me without sudo.

What do you mean by that? Based on the screenshot your sudo password is wrong. Do you have special characters on your sudo password? I might need to rewrite the sudo sanity check

**Comment by dilydaly** [comment]
> > Script does not function correctly for me without sudo.
> 
> What do you mean by that? Based on the screenshot your sudo password is wrong. Do you have special characters on your sudo password? I might need to rewrite the sudo sanity check

I tried running the script the very first time before ever formatting my deck, I had a sudo password set to "p".
No matter how many times I ran it, it would ask for the pass, I would enter it, and it would fail. 
The moment I put ```sudo [script execute]```, it functions correctly and actually checks if the pass is correct instead of failing the check 100% of the time.

This has been the only way for me to even get the script to run, across all steamOS formats, and even changing the password multiple ways. My current temporary password for the deck is  " " as in, one spacebar press or a Y button press on controller. The installer script always requires sudo otherwise it will fail me 100% of the time when asking for the sudo pass.

**Comment by ryanrudolfoba** [comment]
Got it. So the script is having difficulty parsing your sudo password. Mine has been pretty simple - `dexk` for testing purposes and it works without issue.

I'll update the sudo sanity check in the next update.

**Comment by dilydaly** [comment]
I saw the update, re-imaged the entire SSD instead of just formatting the OS, and made an attempt again.

1st try - same results as all the other previous attempts.
2nd try with SUDO before all commands - same results, waydroid installed but shortcuts and folders not created.

Re-imaged again:

1. set passwd to "complexandlongpassword1"

Script works flawlessly, all shortcuts and folders installed correctly, new GAPPS prompt works great.

Toolbox lib patches work great.

So either the issue is it parsing "<space characters>" as a sudo pass, or passwords being shorter than 3 characters.
Possibly the script worked fine the whole time and my password was just too short or should not have contained the space character.


(I usually dont put big passwords on my accounts because I wipe bi-weekly and this deck is exclusively used for emulation)
