### ISSUE TITLE
Not supported kernel in newest SteamOS Beta

### ISSUE THREAD

**Issue by nitolar** [ryanrudolfoba/SteamOS-Waydroid-Installer#167]
![image](https://github.com/user-attachments/assets/5edac376-fc53-4028-b22f-10b03e551359)

Deck Info:
SteamOS ver: 3.6.17 (newest beta)
Kernel version: 6.5.0-valve21-1-neptune-65-g33487bf05ed3
Steam ver: 1728429192

**Comment by ryanrudolfoba** [comment]
This now supports latest SteamOS beta 3.6.16 / 3.6.17.
clone the repo to get the latest version and perform the install.
