### ISSUE TITLE
/VAR Directory To Full

### ISSUE THREAD

**Issue by smabbage** [ryanrudolfoba/SteamOS-Waydroid-Installer#168]
My /VAR directory is to full.  Cannot find a way to make available space to install Waydroid.

**Comment by ryanrudolfoba** [comment]
please share screenshot of the error

**Comment by smabbage** [comment]
![Screenshot_20241011_154343](https://github.com/user-attachments/assets/68f05fab-dd25-494d-acb3-5bc349424e9d)

**Comment by ryanrudolfoba** [comment]
Are you doing a reinstall of Waydroid? Or totally start from scratch?

You need to free up space on the var partition. The script needs at least 60MB on the var, i made it 100MB just to be sure.

**Comment by smabbage** [comment]
This is a reinstall.  The issue is I don't know how or what to remove for the VAR partition to allow the script to run.  This is the first time I've run up against this issue.  I've reinstalled several times, but this is the first time I've received this error.

**Comment by ryanrudolfoba** [comment]
no worries this is because i updated the script yesterday to have this sanity check. I didn't take into consideration for reinstalls. I'll update the script in the next few days to fix this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smabbage** [comment]
Thanks.

**Comment by smabbage** [comment]
I stuck a spoon in the script and stirred a bit.  Reduced the VAR requirement value from 100k to 30k and all installed fine.  Looking forward to a more permanent solution in future.  It's a wonder what a little sleep will do to boost thought processes.  :)

**Comment by ryanrudolfoba** [comment]
additional logic - skip var sanity check if its a reinstall

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/commit/3b69818b90f25104d766da5e7aa176b5b17cc630
