### ISSUE TITLE
won't launch after restart

### ISSUE THREAD

**Issue by pixelyloaf** [ryanrudolfoba/SteamOS-Waydroid-Installer#169]
i've tried installing about 3 times, says it's done and waydroid works the first time, after a system restart this shows up
![image](https://github.com/user-attachments/assets/6e9b9c3b-88ed-480f-a470-e2eaa22267af)

**Comment by ryanrudolfoba** [comment]
SteamOS Waydroid Installer Script has been updated!

What's New (as of Oct 28 2024)
1. Support for latest SteamOS Stable 3.6.19
2. fixed binder kernel module parameters
3. enhancement - ability to choose with / without Google Playstore on a fresh install
4. enhancement - automatically activate mantis gamepad pro and shizuku
5. enhancement - disable root detection (some apps might still detect root)
6. enhancement - disable first time setup wizard
7. enhancement - Waydroid Toolbox - added NETWORK option
8. enhanceement - Waydroid Toolbox - updated ADBLOCK option

This can also be used as an install guide! Make sure you have a sudo password already set and then do the konsole commands!

Moving forward just do the Waydroid-Updater.sh to easily clone and install the latest version of the script!

Upgrade guide here -
https://youtu.be/CJAMwIb_oI0

Happy gaming!

-10MinuteSteamDeckGamer
