### ISSUE TITLE
6.1.52-valve12-1-neptune-61 is NOT supported. Exiting immediately.

### ISSUE THREAD

**Issue by edkodz** [ryanrudolfoba/SteamOS-Waydroid-Installer#17]
6.1.52-valve12-1-neptune-61 is NOT supported. Exiting immediately.

**Comment by ryanrudolfoba** [comment]
What version of SteamOS are you on?

This only supports 3.5.7 and 3.5.13

**Comment by edkodz** [comment]
OS version: 3.5.7
![20240203_120519](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/67428184/3808b49a-3cb8-498d-92f6-9ab13f1da753)

**Comment by edkodz** [comment]
Finally find solution. I run `sudo pacman -Syu && reboot` and it installed - 6.1.52-valve14-1-neptune-61 kernel. Big thanks for yours script, it makes life easier :-)

**Comment by ryanrudolfoba** [comment]
You're welcome! Glad you got it working now.
