### ISSUE TITLE
Error installing binder kernel module

### ISSUE THREAD

**Issue by ArtemisSaber** [ryanrudolfoba/SteamOS-Waydroid-Installer#170]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Checking if home partition has enough free space
home partition has 367655124 free space.
home partition has enough free space.
Checking if var partition has enough free space
var partition has 149552 free space.
var partition has enough free space.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Cloning casualsnek repo.
This can take a few minutes depending on the speed of the internet connection and if github is having issues.
If the git clone is slow - cancel the script (CTL-C) and run it again.
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-11-09
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
cp: cannot stat 'binder/6.1.52-valve16-1-neptune-61/binder_linux.ko.zst': No such file or directory
Error installing binder kernel module. Run the script again to install waydroid.
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by ArtemisSaber** [comment]
Tried multiple times and no luck with that

**Comment by ArtemisSaber** [comment]
(deck@steamdeck ~)$ uname -a
Linux steamdeck 6.1.52-valve16-1-neptune-61 #1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000 x86_64 GNU/Linux

**Comment by ryanrudolfoba** [comment]
sorry for late reply. I just tried this on a fresh SteamOS 3.5.19 install and it works OK.

maybe the git clone command some files were not cloned completely. 

go to the binder folder > 6.1.52-valve16-1-neptune-61

check that there is a file there called binder_linux.ko.zst

**Comment by ryanrudolfoba** [comment]
havent heard back, feel free to update this if further help is needed.

im also will be updating the script to support the latest SteamOS 3.6.19 stable.
