### ISSUE TITLE
Not supported 

### ISSUE THREAD

**Issue by Kotovgihubr** [ryanrudolfoba/SteamOS-Waydroid-Installer#175]
6.5.0-valve22-1-neptune-65 is NOT supported

**Comment by Kotovgihubr** [comment]
Pls fix

**Comment by Taboulet** [comment]
Check https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/171 for more info, but in short it will soon be fixed

**Comment by ryanrudolfoba** [comment]
Duplicate of https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/171
