### ISSUE TITLE
Installer Binder Error

### ISSUE THREAD

**Issue by RetroChristian** [ryanrudolfoba/SteamOS-Waydroid-Installer#176]
cp: cannot stat 'binder/6.5.0-valve22-1-neptune-65/binder_linux.ko.zst': No such file or directory
Error installing binder kernel module.

How do you resolve this issue?

**Comment by Taboulet** [comment]
Ty for uploading an updated guide on that
But we don't have a waydroid Toolbox 0_0
I think the binder glitch end the script right before it adds the toolbox app

**Comment by ryanrudolfoba** [comment]
SteamOS Waydroid Installer Script has been updated!

What's New (as of Oct 28 2024)
1. Support for latest SteamOS Stable 3.6.19
2. fixed binder kernel module parameters
3. enhancement - ability to choose with / without Google Playstore on a fresh install
4. enhancement - automatically activate mantis gamepad pro and shizuku
5. enhancement - disable root detection (some apps might still detect root)
6. enhancement - disable first time setup wizard
7. enhancement - Waydroid Toolbox - added NETWORK option
8. enhanceement - Waydroid Toolbox - updated ADBLOCK option

This can also be used as an install guide! Make sure you have a sudo password already set and then do the konsole commands!

Moving forward just do the Waydroid-Updater.sh to easily clone and install the latest version of the script!

Upgrade guide here -
https://youtu.be/CJAMwIb_oI0

Happy gaming!

-10MinuteSteamDeckGamer
