### ISSUE TITLE
Internet malfunction

### ISSUE THREAD

**Issue by LukiDaku** [ryanrudolfoba/SteamOS-Waydroid-Installer#177]
For some reason I can not download applications from play market, endless “start downloading”, not all sites open, most sites say that there is no connection, although sometimes something is downloaded
If you turn on VPN on the router, everything starts to load and work, I live in Russia and maybe something is partially blocking the Internet I really do not understand how this can be related to the whole system, the Internet is working fine on my PC, phone, etc.

**Comment by ryanrudolfoba** [comment]
Firsr time I've heard of an issue like this.

If the problem goes away after using VPN at the router im afraid there's not much i can do - this points to an internet issue / ISP issue.
