### ISSUE TITLE
[feature request] Support CachyOS Handheld Edition

### ISSUE THREAD

**Issue by Aiakio** [ryanrudolfoba/SteamOS-Waydroid-Installer#178]
Would it be possible to make this compatible with CachyOS Handheld Edition on the Steam Deck? For now the script says, that it appears im not using a Steam Deck. I am, but running CachyOS on it.

**Comment by bizkut** [comment]
CachyOS has waydroid in it's repo. Just install it from CachyOS  Packages Installer.

**Comment by ryanrudolfoba** [comment]
This is only for SteamOS.
