### ISSUE TITLE
SteamOs Update 11/5/2024

### ISSUE THREAD

**Issue by npcjuwow** [ryanrudolfoba/SteamOS-Waydroid-Installer#179]
Valve launched a new version for SteamOs today. As expected, Waydroid is broke. Just letting you know as you instructed  us to.
Thanks for your great work. Have a nice holiday season.

**Comment by ryanrudolfoba** [comment]
Thats fine the latest SteamOS 3.6.20 is using the same kernel from 3.6.19.

Just reinstall the script to have waydroid back.

**Comment by npcjuwow** [comment]
Oh, great!
Sorry for bothering over nothing. I will keep a closer eye to the kernel next time. 
Thanks for the timely reply.
