### ISSUE TITLE
touch input isn't registered as touch input in games

### ISSUE THREAD

**Issue by LhymeFruit** [ryanrudolfoba/SteamOS-Waydroid-Installer#18]
I've tried rec room and call of duty mobile but they both don't work because they require you to click a button but you can't click it because it needs to be a touch screen click.

**Comment by ryanrudolfoba** [comment]
Are you using latest version of the script ?
Are you using cage or weston?
Please use cage and make sure you configure it to use native touchscreen support.

**Comment by LhymeFruit** [comment]
> Are you using latest version of the script ? Are you using cage or weston? Please use cage and make sure you configure it to use native touchscreen support.

I am using the latest script, how do I configure cage?

**Comment by ryanrudolfoba** [comment]
Please check the accompanying demo guide it shows how to configure cage for native touchscreen.

On the cage shortcut screen, click the gamepdad icon. Make sure its set as gamepad + trackpad. Clicik edit > action sets > add always on. Select system > native touchscreen

**Comment by LhymeFruit** [comment]
> Please check the accompanying demo guide it shows how to configure cage for native touchscreen.
> 
> On the cage shortcut screen, click the gamepdad icon. Make sure its set as gamepad + trackpad. Clicik edit > action sets > add always on. Select system > native touchscreen

That fixed the issue but now I have another issue the game crashes the second I hit play, I'm trying rec room. Cod mobile also crashed when it opens

**Comment by ryanrudolfoba** [comment]
Could be isolated game compatibility issue with waydroid. Could be fixed on future waydroid versions. I'll update the script when a new waydroid version is available.
