### ISSUE TITLE
failed to get service waydroidplatform

### ISSUE THREAD

**Issue by napsstern** [ryanrudolfoba/SteamOS-Waydroid-Installer#180]
When I try to install an app using the command 
waydroid app install <filename>

the following message showed up: 
waydroid session stopped

I used the waydroid toolbox to start the waydroid container service 
then when I enter the command again, the following message shows up infinitely:
failed to get service waydroidplatform, trying again... 

Please help! I can't install the app through google play store because that app is not available in the country I am  in

**Comment by napsstern** [comment]
Is it possible to install apks not through google play store? 

I would really appreciate an answer, thank you

**Comment by ryanrudolfoba** [comment]
Yes you can sideload APKs. I've created a guide here -

https://youtu.be/LglEbSdRc0M

**Comment by ryanrudolfoba** [comment]
> I used the waydroid toolbox to start the waydroid container service
then when I enter the command again, the following message shows up infinitely:
failed to get service waydroidplatform, trying again...

That error appears if you are using regular Desktop Mode.
Make sure you are on Nested Desktop as shown in the guide regarding sideloading APKs.
