### ISSUE TITLE
multitouch gesture dose not work

### ISSUE THREAD

**Issue by reincarnatedgrippon** [ryanrudolfoba/SteamOS-Waydroid-Installer#182]
I confirmed that multitouch is working by following the guide you provided.
But the pinch gesture doesn’t seem to work in browser.
Do I have to do additional settings?

**Comment by ryanrudolfoba** [comment]
pinch gesture is working in browser.
make sure to follow the install guide and configure the controller correctly.

Action Sets > Always On Command > Touchscreen Native Support.
