### ISSUE TITLE
kernel version NOT supported

### ISSUE THREAD

**Issue by dreadpirateroberts-OnSteam** [ryanrudolfoba/SteamOS-Waydroid-Installer#183]
I am new to this waydroid emulator...i just tried following all the videos and konsole commands and still keep running into the same issue. "kernel version blah blah blah not supported."

I just got a steamos update like 3 days ago...so i guess thats why it is not supported?

any idea when waydroid will be updated to work on newest steamos? I made a github account just tto ask this question so pwease lmk. thanks and shoutout ryan for making a sick emulator 

"Do not take life to seriously, you will never get out alive."

**Comment by ryanrudolfoba** [comment]
What SteamOS version are you on?

The script has been updated eversince 3.6.19 / 20 went to Stable a few weeks ago. Make sure to clone the repo to get the latest version of the script.

However if you are on SteamOS beta i haven't updated the script yet to work with SteamOS beta.

Best bet is to identify which SteamOSA you are on, or paste a screenshot of the error it contains valuable info.

**Comment by dreadpirateroberts-OnSteam** [comment]
i think i did not properly uninstall it. now its working this go thru. sry for the bother.

**Comment by dreadpirateroberts-OnSteam** [comment]
im getting a "failed to load module appmenu-gtk-module" message

**Comment by ryanrudolfoba** [comment]
can you provide a screenshot where you are getting that error.

**Comment by ryanrudolfoba** [comment]
feel free to update this if need further help.
