### ISSUE TITLE
I can't seem to get past  "Downloading waydroid image from sourceforge"

### ISSUE THREAD

**Issue by lal1tx** [ryanrudolfoba/SteamOS-Waydroid-Installer#186]
![image](https://github.com/user-attachments/assets/c9cf059c-df2e-4016-8da1-a6941d03abd0)

but the waydroid toolbox gets installed and works??

![image](https://github.com/user-attachments/assets/e50da853-bfbf-4a51-af60-4c6f5e3f98fc)

**Comment by ryanrudolfoba** [comment]
so maybe it is having issues with the sourceforge mirror? Did you select GAPPS or NOGAPPS?

**Comment by lal1tx** [comment]
I selected GAPPS, i have not tried NOGAPPS, i will update on it

**Comment by lal1tx** [comment]
welp, NOGAPPS works without problem, that's funny 
![image](https://github.com/user-attachments/assets/36a29336-3cb6-4040-b329-7d6ec05d8e68)

**Comment by lal1tx** [comment]
then its a sourceforge mirror problem i guess, sorry for not trying NOGAPPS before.

**Comment by ryanrudolfoba** [comment]
I've tried GAPPS and it is downloading fine. 2 things - could be an issue with sourceforge or could be an issue with your internet connection.

![image](https://github.com/user-attachments/assets/f6756892-7c49-4c9b-9eea-c09d3f951abe)
