### ISSUE TITLE
Root option for Waydroid in Steam Deck

### ISSUE THREAD

**Issue by d3vC0mm4nd3rShadowSlayer29** [ryanrudolfoba/SteamOS-Waydroid-Installer#188]
I was experiencing some games tagging incompatible due to a device recognized as Pixel 5.
I was searching on the internet on how to change it and found a repo about adding Magisk and even Smart dock in Waydroid but when I try to execute it, it does restart the Waydroid instance but it doesn't install. Requesting assistance if it would be possible to include it in the installation instance.

I also noticed that the certification of Google Play as well is not verified to hence the need to root it.

No pressure. I'm recommending it if it would be possible to add in your installation script.

If you are wondering, I found the script from Casualsnek. The name of the repo is Waydroid_script.

It includes Magisk and Smartdock which I mentioned earlier.

**Comment by casithepup** [comment]
> and no you cant root waydroid using magisk on SteamOS. i've tried several months ago and it doesnt work.

Is it possible that you could look into this again? It does seem to work (I'm using Android 11 no GAPPS), but the modifications that wayland_script made, disabled the deck's controls.
