### ISSUE TITLE
latest SteamOS 3.7-update, changes.

### ISSUE THREAD

**Issue by slynobody** [ryanrudolfoba/SteamOS-Waydroid-Installer#190]
Valve shipped a new version of SteamOS these days, kernel 6.8.12.

It killed some parts of the former installation-method. not only the binder-module had to be updated but nearly all other precompiled packages too. This seem to result largely on the appearance of python 3.12 in this build (beside other changes like plasma 6.2, mesa 24 and others).
I suppose it is the first reflecting relatively large changes in SteamOS to come that could make it  to beta in the next month.

So just for your info. (6.8.12.valve7-1 does not even include the 'git'-command anymore, building yay and the needed packages had a few, partly non-trivial hickups too)

The 3.7-build should work now: https://github.com/slynobody/SteamOS-Waydroid-Installer. Lets see what happens next.

**Comment by ryanrudolfoba** [comment]
thanks for the heads up. i dont use MAIN but definitely this is good info once it rolls out to PREVIEW / BETA.

**Comment by ryanrudolfoba** [comment]
regarding git, fhis is fixed now on latest MAIN -

https://github.com/ValveSoftware/SteamOS/issues/1732#issuecomment-2511174125
