### ISSUE TITLE
Will Nobara Steam Deck be supported?

### ISSUE THREAD

**Issue by robertpro** [ryanrudolfoba/SteamOS-Waydroid-Installer#191]
./steamos-waydroid-installer.sh
```shell
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
SteamOS 40 - kernel version 6.11.9-200.fsync.fc40.x86_64 is NOT supported. Exiting immediately.
```

**Comment by robertpro** [comment]
@ryanrudolfoba Can you guide me what places should I look on the script in order to support it myself? Also, if I make it work for Nobara, will you accept a PR ?

**Comment by ryanrudolfoba** [comment]
Nobara is based on Fedora, while SteamOS is based on archlinux. Two separate things - this script and the executables won't work as the underlying OS are totally different.

Check Nobara maybe waydroid is in the repos.

**Comment by robertpro** [comment]
I know, I'm running Nobara Steam Deck on my Steam Deck: https://nobaraproject.org/docs/steamdeck-edition/add-steam-deck-mode-to-existing-nobara-installation/

**Comment by ryanrudolfoba** [comment]
So what happens when you try search waydroid in the repos?

**Comment by robertpro** [comment]
It is found, just like Fedora (Nobara is based on Fedora), I can actually install waydroid that way, but I would like to install it automatically with your script, so it is also managed with the Deck Mode.

**Comment by ryanrudolfoba** [comment]
install waydroid from the repo. then launch it see if it works. it should work right away as i test waydroid on my fedora box too.

once that is done, you need `cage` and `wlr-randr`. im not sure if those are on the repos.

**Comment by robertpro** [comment]
Cool, that's a good starting point, thanks!

**Comment by robertpro** [comment]
And yes, they both are on the repos.

**Comment by ryanrudolfoba** [comment]
ok cool install those and you're halfway done.

lines 190-318 and 403-456 is what you need to adapt to your install.
