### ISSUE TITLE
Error installing waydroid and cage

### ISSUE THREAD

**Issue by Flicker2024** [ryanrudolfoba/SteamOS-Waydroid-Installer#192]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-InstallerYT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
SteamOS 3.5.19 - kernel version 6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Checking if home partition has enough free space
home partition has 205891684 free space.
home partition has enough free space.
Checking if var partition has enough free space
var partition has 204128 free space.
var partition has enough free space.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Cloning casualsnek repo.
This can take a few minutes depending on the speed of the internet connection and if github is having issues.
If the git clone is slow - cancel the script (CTL-C) and run it again.
Casualsnek repo has been successfully cloned!
Warning: The rootfs is already read-write!         
Nothing is performed.
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2025-01-01
pacman keyring has been initialized!
Binder kernel module not found or not up to date! Installing binder!
Binder kernel module has been installed!
Error installing waydroid and cage. Run the script again to install waydroid.
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

**Comment by Flicker2024** [comment]
BTW the SteamOS version is 3.5.19. Do I need to update to 3.6.20?

**Comment by ryanrudolfoba** [comment]
sorry for late reply. so it is getting an error on this part of the script -
![image](https://github.com/user-attachments/assets/f92f44bd-997c-4429-b655-4eb52da9e5a2)


can you try manually running this command - \
cd ~/steamos-waydroid-installer \
sudo -S pacman -U cage/wlroots-0.16.2-1-x86_64.pkg.tar.zst --noconfirm --overwrite "*"

**Comment by Flicker2024** [comment]
It worked, thank you for your support!
