### ISSUE TITLE
Kernel 6.5.0-valve23-1-neptune-65 is NOT supported.

### ISSUE THREAD

**Issue by TheSixtyFour** [ryanrudolfoba/SteamOS-Waydroid-Installer#194]
Just updated to the newest SteamOS Beta and I got prompted to reinstall Waydroid running the script.
However, I received the "6.5.0-valve23-1-neptune-65 is NOT supported. Exiting immediately." when I tried re-running the script.

From what I've read in other issues, the Binder needs to be updated.

Just putting it out there so that it can be updated, Thanks in advance!

**Comment by ryanrudolfoba** [comment]
That looks like the latest beta released a few days ago. This will need an update to the binder kernel module.

**Comment by ryanrudolfoba** [comment]
script has been updated to support latest SteamOS 3.6.21 beta

![image](https://github.com/user-attachments/assets/9d840318-5553-4417-9182-2f581692623d)
