### ISSUE TITLE
how to change the refresh rate from 60 to 90?

### ISSUE THREAD

**Issue by stellaloveslinux** [ryanrudolfoba/SteamOS-Waydroid-Installer#203]
ive changed the script to do 90hz, but android is still reporting 60hz
![image](https://github.com/user-attachments/assets/dd0293c1-751c-40d8-86d8-e63f7672df2a)

**Comment by ryanrudolfoba** [comment]
this seems to be a limitation in Waydroid itself it is locked to 60FPS

**Comment by stellaloveslinux** [comment]
> this seems to be a limitation in Waydroid itself it is locked to 60FPS

it literally isnt, on my pc its 240 hz because my monitor is.

**Comment by ryanrudolfoba** [comment]
What OS do you use on your PC? How do you launch Waydroid in there?

**Comment by stellaloveslinux** [comment]
> What OS do you use on your PC? How do you launch Waydroid in there?

arch linux

**Comment by ryanrudolfoba** [comment]
> > What OS do you use on your PC? How do you launch Waydroid in there?
> 
> arch linux

Please provide more details -

How do you launch Waydroid in there?

Do you also use gamescope to be able to monitor the FPS?
