### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Duality4Y** [ryanrudolfoba/SteamOS-Waydroid-Installer#207]
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/blob/7efe7d6d963d817a6e60cfe6aac4502e31c757b7/steamos-waydroid-installer.sh#L347

I just noticed this while installing, it says sript instead of script?

**Comment by ryanrudolfoba** [comment]
fixed the minor typo

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/commit/12a9da530cf21a354e34a61c2b3b9025654d370e
