### ISSUE TITLE
no module named dbus

### ISSUE THREAD

**Issue by jurassicjordan** [ryanrudolfoba/SteamOS-Waydroid-Installer#21]
chmod: cannot operate on dangling symlink '/dev/anbox-binder'
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'

I also saw this during install.

**Comment by ryanrudolfoba** [comment]
What version SteamOD are you on?
Try to uninstall / reinstall.

**Comment by ryanrudolfoba** [comment]
havent heard back for few days. please feel free to re-open if youre still having issues.
