### ISSUE TITLE
Add option to reduce audio latency using scrcpy

### ISSUE THREAD

**Issue by DerpyChap** [ryanrudolfoba/SteamOS-Waydroid-Installer#22]
Waydroid appears to have a [significant amount of audio latency](https://github.com/waydroid/waydroid/issues/613), to the point where rhythm games become impossible to play unless you adjust the audio latency in the game's settings.

By using [`scrcpy`](https://github.com/Genymobile/scrcpy), you can significantly reduce the amount of audio latency.

Using the game Cytoid as an example, here's the amount of measured end-to-end latency in the game's calibration tool when using Waydroid's audio playback:

![15324628_20240204220644_1](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/15108194/a65d08c7-754b-441a-9dc9-4ab6b980dd0d)

When running `scrcpy --audio-buffer 30 --audio-codec=raw --no-video-playback --tcpip=[WAYDROID_IP_ADDRESS]:5555` via SSH I measured the following latency:

![15324628_20240204221513_1](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/15108194/b67d4005-86e4-4c11-8651-c01b78d4c525)

For a rough idea of how this compares to an actual Android device, I ran the same test on my Sony Xperia 1 II.

![Screenshot_20240204-222604](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/15108194/391e406e-66c5-489c-b913-cff3a5a64c7b)

This results in roughly half the end-to-end audio latency of Waydroid's native audio output, and brings things much closer to an actual Android device. I tried lower values for `--audio-buffer`, but it resulted in some noticeable popping in the audio. I haven't noticed any issues in more demanding games that I have tested, but despite that it might be best to make such a feature default off just in case.

**Comment by ryanrudolfoba** [comment]
i'd have to read up on it and wrap my head how to implement it on the script.

**Comment by ActualMandM** [comment]
Does 20 audio buffer crackle on your end? I tried it with Project Sekai and it worked fine for me. (plus it *just* manages to work with the game's -20/20 limit)

**Comment by ryanrudolfoba** [comment]
I think i know how to add this to the script. Will there be any negative effect if default to 25?

**Comment by DerpyChap** [comment]
I didn't notice any issues when set to 25, but I haven't done any extensive testing.

**Comment by DerpyChap** [comment]
So I originally [glanced over this](https://github.com/waydroid/waydroid/issues/613#issuecomment-1759302508) in the original Waydroid issue since they said they had "little success", but in my testing it at gets audio latency down much closer to `scrcpy`.

Overlaying `/system/etc/init/audio.rc` containing the following:
```shell
 on init
    export PULSE_LATENCY_MSEC 60
    export PIPEWIRE_LATENCY 24/48000
```

reduces latency significantly. I tried setting `PULSE_LATENCY_MSEC` lower but it just resulted in there being no audio, although as far as I am aware the Steam Deck uses Pipewire for audio playback, so the `PIPEWIRE_LATENCY` environment variable should be the one that matters here? Admittedly I'm not all that familiar with how audio works on Linux so I'm not 100% certain there.

@ActualMandM how would you say this compares to `scrcpy`?

**Comment by ActualMandM** [comment]
The delay in the calibration is pretty bad with this still, even with it set to -20. I'm able to get it set to 50 on my end without audio being missing.

**Comment by ryanrudolfoba** [comment]
Here's my findings using scrcpy and cytoid -

without scrcpy - 0.429s offset
with scrcpy 30 buffer - 0.277s
with scrcpy 25 buffer - 0.293s
with scrcpy 20 buffer - 0.302s

So it looks like the sweet spot is the 30 buffer?
btw i noticed if scrcpy is enabled the audio becomes very faint compared to when its turned off, do you guys get the same behavior?

It could also be my version of scrcpy. The one from pacman repo is old 2.0.x and doesnt support the no-video-playback parameter. I build from git source to get the latest 2.3.x.

What version do you guys use for scrcpy and where did you get it?

**Comment by ryanrudolfoba** [comment]
here's how to have scrcpy launch automatically in Game Mode -

create a file - /usr/bin/waydroid-fix-audio and make the file executable. Contents of the file -
#!/bin/bash
scrcpy --audio-buffer 30 --audio-codec=raw --no-video-playback

Edit the file ~/Android_Waydroid/cage_helper.sh and add at the end -

sleep 5
/usr/bin/waydroid-fix-audio

Please test and i can add this to the next version.

**Comment by ryanrudolfoba** [comment]
Using the overlay audio.rc method the cytoid offset shows 0.171s

I used this -
 on init
    export PULSE_LATENCY_MSEC 60
    export PIPEWIRE_LATENCY 24/48000

So i guess this is the way to go? Much cleaner too as no extra binaries needed, and my audio is not faint compared to when scrcpy is enabled.

**Comment by DerpyChap** [comment]
> So it looks like the sweet spot is the 30 buffer? btw i noticed if scrcpy is enabled the audio becomes very faint compared to when its turned off, do you guys get the same behavior?
> 
> It could also be my version of scrcpy. The one from pacman repo is old 2.0.x and doesnt support the no-video-playback parameter. I build from git source to get the latest 2.3.x.
> 
> What version do you guys use for scrcpy and where did you get it?

I installed it from `nix`, which I believe has the latest release. The audio sounded the same for me when using `scrcpy`. I'd recommend installing the latest `scrcpy` release and re-testing.

**Comment by ActualMandM** [comment]
> So it looks like the sweet spot is the 30 buffer? btw i noticed if scrcpy is enabled the audio becomes very faint compared to when its turned off, do you guys get the same behavior?

I had to turn the volume back up in settings once connecting scrcpy. I grabbed v2.1 from the Arch Linux archive because the latest version gave me an outdated glibc error.

**Comment by ActualMandM** [comment]
> The delay in the calibration is pretty bad with this still, even with it set to -20. I'm able to get `PULSE_LATENCY_MSEC` set to 50 on my end without audio being missing.

I probably should've test it on 0 whoops, it seems to sync up pretty well.

**Comment by ryanrudolfoba** [comment]
I'm leaning on the audio.rc method too as no extra binaries needed.

**Comment by DerpyChap** [comment]
Yeah, using the `audio.rc` file seems to be the most ideal solution. Don't think there's anything else that can reduce latency further without reworking how Waydroid handles audio altogether.

**Comment by ryanrudolfoba** [comment]
Awesome. What willl be the best default values to include on the script?

**Comment by DerpyChap** [comment]
I'd probably go with either `32/48000` or `64/48000` since that gives us a bit of a buffer (around 1.2ms with 64) which could help reduce the likelihood of audio popping from high CPU loads.

`PULSE_LATENCY_MSEC` seems to have a hard limit of 50-60, although I'm not sure if that option is doing much on the Deck anyway.

**Comment by ryanrudolfoba** [comment]
50msec and 32/48000 resulted in 0.164s. sweet!

**Comment by ryanrudolfoba** [comment]
pushed the proposed config and updated the installer script.

**Comment by ryanrudolfoba** [comment]
> Awesome. What willl be the best default values to include on the script?
> 
> Moving forward I plan to include a "waydroid toolbox" that user runs in Desktop Mode if they want to change the default values. It will just be a simple zenity-based menu and user can choose -
> 
> disable / enable custom host file toggle between libndk / libhoudini delete current android image and reinitialize a new one disable / enable audio latency fix

preliminary Waydroid Toolbox is now here on the latest version
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/92acedaf-8828-4573-adfa-6b76f346ced4)

at the moment cant implement toggle between libhoudini / libndk - the var partition is tiny libhoudini doesnt fit. libndk is small so we are good with that.
