### ISSUE TITLE
Could not resolve the "weston" dependency "colord"

### ISSUE THREAD

**Issue by leehans** [ryanrudolfoba/SteamOS-Waydroid-Installer#23]
Using the latest installer script, I am running into an issue where the package "colord" could not be resolved properly. It results into weston not properly  setup/upgraded, which then makes the installation fail. Following is the few lines of warnings and ultimately error that is logged. 

```
warning: database file for 'jupiter-rel' does not exist (use '-Sy' to download)
warning: database file for 'holo-rel' does not exist (use '-Sy' to download)
warning: database file for 'core-rel' does not exist (use '-Sy' to download)
warning: database file for 'extra-rel' does not exist (use '-Sy' to download)
warning: database file for 'community-rel' does not exist (use '-Sy' to download)
warning: database file for 'multilib-rel' does not exist (use '-Sy' to download)
loading packages...
resolving dependencies...
warning: cannot resolve "colord", a dependency of "weston"
:: The following package cannot be upgraded due to unresolvable dependencies:
      weston

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'colord' required by weston
Error installing waydroid and cage. Goodbye!
```

I am on StetamOS stable.

**Comment by ryanrudolfoba** [comment]
Please try to uninstall, clone the repo again to get the latest version and try to install.
I've tested the script on vanilla SteamOS 3.5.7, 3.5.13 and 3.5.14. Do you have other scripts / tweaks that might be causing issue?

**Comment by ryanrudolfoba** [comment]
I've updated the script and removed the weston dependency. ive been testing cage for several weeks now and imho it is way better than weston.

Please perform uninstall, clone the repo again to get the latest version, then install.

**Comment by leehans** [comment]
Latest installer script works. Just a heads up, the first time I ran it, I encountered the following:

```
[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
ERROR: Cannot locate waydroid config file, reinit wayland and try again!
Error with casualsnek script.
tee: /var/lib/waydroid/waydroid_base.prop: No such file or directory
```

This was right before the shortcuts in game mode were being generated. The installation finished, but waydroid wouldn't launch (it was crashing from black screen 2-3 seconds after running the app in game mode).

I uninstalled (even removed the cloned repo), and redid the steps and it worked this time. I am guessing some config or path is being created during the installation, but would trigger this error if it wasn't there the first time around. Or something of the sort. 

Anyway, it works now! Can confirm One-Punch Man World works, although the main game I wanted to try (Ragnarok X: Next Generation) was crashing on launch for some reason. Could be some proton-related issue (maybe?). I am investigating that. But for now, feel free to close this issue, salamat kapatid!

**Comment by ryanrudolfoba** [comment]
thank you for the feedback!

i've created a google sheet if you want to continue game testing please put your data in there. thank you!

google sheets link -

https://docs.google.com/spreadsheets/d/1pyqQw2XKJZBtGYBV0i7C510dyjVSU2YndhaTOEDavdU/edit?usp=sharing

**Comment by leehans** [comment]
no worries!

i had been thinking of suggesting the same. this sheet will really help.
i'll continue to put in new stuff whenever i can, thanks!
