### ISSUE TITLE
Minecraft Controls issue

### ISSUE THREAD

**Issue by ozomax1997** [ryanrudolfoba/SteamOS-Waydroid-Installer#24]
the controls for Minecraft are glitched, the right stick and trigger move the camera

**Comment by ryanrudolfoba** [comment]
Please clone the repo and perform the install again. That should fix the controller issue.

**Comment by ozomax1997** [comment]
do I need to uninstall prior? I installed using latest method.

**Comment by ryanrudolfoba** [comment]
clone the repo and just run the install again.

**Comment by Pokepunch** [comment]
I can confirm the controls work as expected on the latest version.

**Comment by Timbo303** [comment]
Sadly have this issue too which the latest steamos stable build. Disabling steam input doesnt work for external controllers either. This is not a minecraft only issue its a waydroid issue and this one is often common on androids.

**Comment by Butterscotch96** [comment]
Not really helping the issue but there is an app called Minecraft bedrock launcher or something that just does some dark magic with the Android version to run it natively. You could try that instead until this is fixed. Might run better anyway.

**Comment by ryanrudolfoba** [comment]
Controller works on Minecraft. If you havent, please clone the latest version of the script.
