### ISSUE TITLE
Waydroid download

### ISSUE THREAD

**Issue by basicJavaCoder** [ryanrudolfoba/SteamOS-Waydroid-Installer#26]
Hi
The download part of the install script where it gets Waydroid from Sourceforge is taking way way too long, I have downloaded the image manually from that link instead
Where should I put the downloaded zip file so the script can continue?

**Comment by ryanrudolfoba** [comment]
when that happens most probably it connected to a slow sourceforge mirror. press CTRL-C to cancel the download and run the script again.

**Comment by basicJavaCoder** [comment]
4th try the charm! oop

**Comment by basicJavaCoder** [comment]
Just got to keep running the script until its proper speed
