### ISSUE TITLE
Game tests

### ISSUE THREAD

**Issue by The-MAZZTer** [ryanrudolfoba/SteamOS-Waydroid-Installer#29]
Tried a few games, all from Play Store

Godville - Works
Clicker Heroes - Works
Pokemon Go - Asks for date of birth, but UI is not interactable so can't proceed (probably won't work anyway due to Safetynet, and lack of GPS)
Pokemon TCG Live - Numerous Wayland bugs during the first run wizard that are difficult to work around, and random crashes that reset everything Didn't have the patience to see if it's possible to get past the login screens.*
Pokemon Masters Ex - Errors and loops (99.9% sure this is its Safetynet check)

* - Letterboxed, but software keyboard does not properly work in letterbox mode making it unusable. Hardware keyboard keys all are interpreted as double presses. Some message boxes in the app open partly off screen.

**Comment by ryanrudolfoba** [comment]
Thanks for the feedback! I have updated the github readme with your game test results.

**Comment by ryanrudolfoba** [comment]
i've created a google sheet if you want to continue game testing please put your data in there. thank you!

google sheets link -

https://docs.google.com/spreadsheets/d/1pyqQw2XKJZBtGYBV0i7C510dyjVSU2YndhaTOEDavdU/edit?usp=sharing

**Comment by djfaizp** [comment]
> Tried a few games, all from Play Store
> 
> Godville - Works Clicker Heroes - Works Pokemon Go - Asks for date of birth, but UI is not interactable so can't proceed (probably won't work anyway due to Safetynet, and lack of GPS) Pokemon TCG Live - Numerous Wayland bugs during the first run wizard that are difficult to work around, and random crashes that reset everything Didn't have the patience to see if it's possible to get past the login screens.* Pokemon Masters Ex - Errors and loops (99.9% sure this is its Safetynet check)
> 
> * * Letterboxed, but software keyboard does not properly work in letterbox mode making it unusable. Hardware keyboard keys all are interpreted as double presses. Some message boxes in the app open partly off screen.

can we play pogo now ??  any fix or patches ???
