### ISSUE TITLE
Pacman dependancies already installed - counts as an error.

### ISSUE THREAD

**Issue by LhymeFruit** [ryanrudolfoba/SteamOS-Waydroid-Installer#3]
Full konsole output 
steam OS 3.5.7
 
`SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
VERSION_ID=3.5.7
SteamOS 3.5.x detected. Proceed with the script.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
So far so good!
Warning: The rootfs is already read-write!
         Nothing is performed.
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2023-12-18
Pacman has been initialized!
Cloning into '/home/deck/AUR/waydroid/waydroid'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 93 (delta 16), reused 93 (delta 16), pack-reused 0
Receiving objects: 100% (93/93), 23.22 KiB | 204.00 KiB/s, done.
Resolving deltas: 100% (16/16), done.
Cloning into '/home/deck/AUR/waydroid/binder_linux-dkms'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 54 (delta 11), reused 54 (delta 11), pack-reused 0
Receiving objects: 100% (54/54), 14.54 KiB | 7.27 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Cloning into '/home/deck/AUR/waydroid/python-gbinder'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 39 (delta 8), reused 39 (delta 8), pack-reused 0
Receiving objects: 100% (39/39), 6.71 KiB | 6.71 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Cloning into '/home/deck/AUR/waydroid/libgbinder'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 56 (delta 21), reused 56 (delta 21), pack-reused 0
Receiving objects: 100% (56/56), 7.22 KiB | 7.22 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Cloning into '/home/deck/AUR/waydroid/libglibutil'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 48 (delta 15), reused 48 (delta 15), pack-reused 0
Receiving objects: 100% (48/48), 6.66 KiB | 6.66 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Cloning into '/home/deck/AUR/waydroid/waydroid_script'...
remote: Enumerating objects: 670, done.
remote: Counting objects: 100% (316/316), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 670 (delta 263), reused 237 (delta 217), pack-reused 354
Receiving objects: 100% (670/670), 21.72 MiB | 8.39 MiB/s, done.
Resolving deltas: 100% (411/411), done.
No errors encountered downloading from AUR.
:: There are 26 members in group base-devel:
:: Repository holo-rel
   1) archlinux-keyring
:: Repository core-rel
   2) autoconf  3) automake  4) binutils  5) bison  6) debugedit  7) fakeroot  8) file
   9) findutils  10) flex  11) gawk  12) gcc  13) gettext  14) grep  15) groff  16) gzip
   17) libtool  18) m4  19) make  20) pacman  21) patch  22) pkgconf  23) sed  24) sudo
   25) texinfo  26) which

Enter a selection (default=all): 
warning: downgrading package archlinux-keyring (20230504-1 => 20221123-1.1)
warning: downgrading package binutils (2.40-6 => 2.39-3)
warning: downgrading package file (5.44-3 => 5.43-1)
warning: downgrading package findutils (4.9.0-3 => 4.9.0-1)
warning: downgrading package gawk (5.2.2-1 => 5.2.0-3)
warning: downgrading package gettext (0.21.1-5 => 0.21.1-1)
warning: downgrading package grep (3.11-1 => 3.8-2)
warning: downgrading package gzip (1.12-2 => 1.12-1)
warning: downgrading package libtool (2.4.7+4+g1ec8fa28-3 => 2.4.7-5)
warning: downgrading package pacman (6.0.2-7 => 6.0.1-8)
warning: downgrading package sed (4.9-3 => 4.8-1)
warning: downgrading package sudo (1.9.13.p3-1 => 1.9.11.p3-1)
warning: downgrading package which (2.21-6 => 2.21-5)
warning: downgrading package glibc (2.37-3.2 => 2.36-6)
warning: downgrading package glib2 (2.76.3-1 => 2.74.0-2)
warning: downgrading package linux-api-headers (6.3-1 => 5.18.15-1)
error: target not found: linux-neptune-61-headers
warning: downgrading package python (3.11.3-2 => 3.10.8-2)
Error installing pacman dependencies. good bye!
(deck@steamdeck steamos-waydroid-installer)$ 
`

**Comment by LhymeFruit** [comment]
after looking at the log, it seems like the scripts expect me not to have any of the dependencies but since I already have them the script thinks there is an error with installing the programs as it didnt turn out to be "installed." I believe the fix for this is to incorperate a check for the dependencies before installing them and then skipping the installation if they are detected as installed. Or add "-overwrite" to the install prompt.

**Comment by ryanrudolfoba** [comment]
i'm rewriting the script so it doesnt pull packages from the pacman repo. tested with binder module and it works. gonna continue with the rest of the script.

**Comment by LhymeFruit** [comment]
> i'm rewriting the script so it doesnt pull packages from the pacman repo. tested with binder module and it works. gonna continue with the rest of the script.

sweet, good luck with that.

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
