### ISSUE TITLE
Bluetooth keyboard key presses interpreted as double presses

### ISSUE THREAD

**Issue by The-MAZZTer** [ryanrudolfoba/SteamOS-Waydroid-Installer#30]
May apply to all hardware keyboards, not sure. Seems to be something that should be fixable. Possibly two different methods are being used to send keypresses to Android. Disable one?

When I type with a hardware keyboard key presses are doubled, both visible characters and control keys.

For example if I try to type "The MAZZTer" I get "TThhee  MMAAZZZZTTeerr"

**Comment by ryanrudolfoba** [comment]
i'm able to replicate this using my wireless (non bluetooth) USB keyboard.
issue happens if i plug in my keyboard AFTER waydroid has started.
quick fix - plug your keyboard BEFORE launching waydroid.
