### ISSUE TITLE
Games tested

### ISSUE THREAD

**Issue by Dooglesmile** [ryanrudolfoba/SteamOS-Waydroid-Installer#32]
Very Little Nightmares - The Google store says "This tablet isn't compatible with the app", and so won't install. It is a pity, as this is the only game I've actually bought from the Google store for my phone. This one does install and work using BlueStacks on Windows.

The Simpsons Tapped Out - Installs and lets me log in. It does keep losing connection, but it does that on my phone, android tablet, my mum's ipad etc. So that's nothing to do with Waydroid.
It works for the most part, but I did notice that every time I click to play one of the minigames, it kicks me to the Waydroid desktop. The game is still running, but disconnected in the background.

**Comment by ryanrudolfoba** [comment]
I'll close this, but please feel free to add games that you have tested on Android Waydroid Steam Deck and I will update the github accordingly. Thank you!

**Comment by ryanrudolfoba** [comment]
i've created a google sheet if you want to continue game testing please put your data in there. thank you!

google sheets link -

https://docs.google.com/spreadsheets/d/1pyqQw2XKJZBtGYBV0i7C510dyjVSU2YndhaTOEDavdU/edit?usp=sharing
