### ISSUE TITLE
"6.1.52-valve16-1-neptune-61 is NOT supported. Exiting immediately."

### ISSUE THREAD

**Issue by Articade** [ryanrudolfoba/SteamOS-Waydroid-Installer#33]
New Steam Version for Steam Deck, not supported.  Just wanted to make you aware.

**Comment by ryanrudolfoba** [comment]
Is this on latest SteamOS Preview channel? I only build for Stable and Preview.

**Comment by Articade** [comment]
This is the latest beta.  They updated it yesterday

**Comment by ryanrudolfoba** [comment]
Thanks for heads up. I'll take a look on the weekend

**Comment by ryanrudolfoba** [comment]
Updated the script. This now support latest SteamOS Preview 3.5.15 - kernel 6.1.52-valve16-1-neptune-61

![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/a8ae4345-60de-4655-be91-aca1b30e7b71)
