### ISSUE TITLE
install successful but Game Mode shortcut exits after black screen.

### ISSUE THREAD

**Issue by krittinen** [ryanrudolfoba/SteamOS-Waydroid-Installer#35]
I installed waydroid using this method after a failed attempt to install using https://gist.github.com/Saren-Arterius/c5bc39199552a5c244449b0ce467d6b6

The install was successful and added the game mode shortcut but going back to Game Mode and launching it results in a black screen then exiting.

I'm running SteamOS preview 3.5.14 build 20240202.2 on LCD

**Comment by ryanrudolfoba** [comment]
The other repo you used might have remnants that is interfering with my script. If you can, try to uninstall / revert the changes you did from the other repo, and run the install script again from my repo.

Script was tested on vanilla SteamOS 3.5.7 and 3.5.14 no other scripts / tweaks installed.

**Comment by krittinen** [comment]
That did the trick!

**Comment by krittinen** [comment]
Uninstalled remnants of previous attempt then reinstalled using this script.
