### ISSUE TITLE
Can't install apps using Play Store, stuck on waiting or pending

### ISSUE THREAD

**Issue by Idontknowman123** [ryanrudolfoba/SteamOS-Waydroid-Installer#36]
What the title says, followed the video, no problems during waydroid installation but can't download apps.

**Comment by ryanrudolfoba** [comment]
Give it a few minutes. Playstore updates after a fresh install. After that you can access it.

**Comment by ryanrudolfoba** [comment]
Give it a few minutes. Playstore updates after a fresh install. After that you can access it.
