### ISSUE TITLE
Can't install this Online Shopping App

### ISSUE THREAD

**Issue by WreckageBrother** [ryanrudolfoba/SteamOS-Waydroid-Installer#38]
https://play.google.com/store/apps/details?id=com.daraz.android

Any way to make it work?

**Comment by WreckageBrother** [comment]
> What error?

Doesn't install. I think it's Waydroid issue.

**Comment by Mstereme** [comment]
I have a theory about the cause. Most apps, despite having internet access, seem to check for Wi-Fi or 4G. If neither of these is being used, they either don’t open or keep showing an offline status.

**Comment by ryanrudolfoba** [comment]
try to sideload the app. i've created a guide on how to sideload apps -

https://youtu.be/LglEbSdRc0M?si=US_Sl_41LPxy-pM_
