### ISSUE TITLE
var partition issues

### ISSUE THREAD

**Issue by Mstereme** [ryanrudolfoba/SteamOS-Waydroid-Installer#39]
“I’m having trouble installing scripts on Waydroid on my Steam Deck due to the size of only 256 MB of the var partition. Is there any possibility to change the installation to the deck’s home?”

**Comment by ryanrudolfoba** [comment]
The script already does that - it creates a symlink to /home/deck/waydroid because /var is tiny.

What version SteamOS are you on?

Can you post a acreenshot of your error?
Add this too -

ls -lh /var/lib
ls -lh ~/
du -sh ~/
df -h

**Comment by Mstereme** [comment]
“Thank you for responding, so, my OS is 3.5.7 and, it seems, in my attempts it did not result in a symlink but in a full installation in var, even my partition manager accused the presence of the file, so I was not able to install the scripts from casualsnek (https://github.com/casualsnek/waydroid_script)”
![Screenshot_20240211_220029](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/109903152/f312a6a1-57ac-47ba-96ca-3d03d0fe6cdd)

**Comment by Mstereme** [comment]
“I can see that some files are symlink within the folder but the scripts that come to be installed like those of casualsnek, these are 100% in var.”
![Screenshot_20240211_221528](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/109903152/98f37e42-24ad-40ae-a131-59640f82aaa4)

**Comment by ryanrudolfoba** [comment]
The bulk of the waydroid file is in the images and cache_http directory. Those are symlink to /home/deck/waydroid or else the image wont download due to the limited space in /var.

Casualsnek script it wont work if you symlink that. That needs to go to /var, and the casualsnek files are tiny it wont fill the whole /var partition.

On your screenshot it shows that /var has 143MB free.

**Comment by Mstereme** [comment]
“It’s nice to know about the scripts inside, so I don’t need CasualSnek. I was just trying to make Brawl Stars work like I did with Wild Rift, but I don’t believe that I can do it in the current state of development.”
