### ISSUE TITLE
The latest linux-neptune-61-headers package is newer than the kernel used in 3.5.7

### ISSUE THREAD

**Issue by Ryhon0** [ryanrudolfoba/SteamOS-Waydroid-Installer#4]
The latest version of `linux-neptune-61-headers` is targeting `6.1.52.valve10-1` while the kernel version used in 3.5.7 is `6.1.52-valve9-1`. If the user updated the package database, it will download the incorrect version of the headers and it won't build the binder module. The headers should be downloaded directly with `pacman -U` instead `-S`

**Comment by ryanrudolfoba** [comment]
im able to build the binder module using 3.5.7, 3.5.9 and the latest 3.5.10

I'll try the command you suggested and check the behavior.

**Comment by cosminmocan** [comment]
@ryanrudolfoba I can duplicate the same issue on my deck , latest stable 3.5.7

Sorry for pic, I am in vacation with no other computer than the deck
![20231213_162551](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/20535086/0698d293-3634-4189-9a24-d54f89f581ec)

@Ryhon0 trying your suggestion did not work for me, errored with "could not find or read package".

Regards , and thank you both for cmaking and contributing to this awesome script

**Comment by Ryhon0** [comment]
You need to manually download the older package from https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/ and install the package with`-U`

**Comment by mikmikmikmik** [comment]
Do you mean modifying the script like this?

# ok so far so good lets install the dependecies
echo -e "$current_password\n" | sudo -S pacman -S --noconfirm fakeroot base-devel glibc glib2 linux-api-headers --overwrite "*" 
echo -e "$current_password\n" | sudo -S pacman -U --noconfirm ./linux-neptune-61-headers-6.1.52.valve9-1-x86_64.pkg.tar.zst --overwrite "*" 
echo -e "$current_password\n" | sudo -S pacman -S --noconfirm python3 lxc dnsmasq weston --overwrite "*"

**Comment by mikmikmikmik** [comment]
What happened to the first two lines. I edit it and the * is in there. I save it and looking above, the first two lines * is missing.

**Comment by ryanrudolfoba** [comment]
i've updated my SteamOS to 3.5.12. Gonna check if it pulls the correct kernel header.

**Comment by mikmikmikmik** [comment]
Thank you very much. I'll wait for your feedbackon this and if clover needs to be updated cos of this minor sream update.

**Comment by ayunami2000** [comment]
> i'm rewriting the script so it doesnt pull packages from the pacman repo. tested with binder module and it works. gonna continue with the rest of the script.

Any updates on the new script?

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
