### ISSUE TITLE
Wifi check issues

### ISSUE THREAD

**Issue by Mstereme** [ryanrudolfoba/SteamOS-Waydroid-Installer#40]
I noticed that some applications, despite having access to the internet, do not work because they simply check the waydroid's wifi and say that it is turned off, as in most multiplayer games and chinatown wars, which does not connect to the rockstar account, some way of implementing fake wifi in the future?

**Comment by ryanrudolfoba** [comment]
i only noticed it in asphalt 8 although i haven't tested a bunch of android games. I plan on creating a guide soon how to do fake wifi.

**Comment by sergius02** [comment]
Same error with Diablo immortal, i think it checks for wifi connection in the first launch to accept the terms and update the launcher. But it show an error message about internet connection.

**Comment by ryanrudolfoba** [comment]
You'd have to configure fake wifi -

waydroid prop set persist.waydroid.fake_wifi packageName

I've created a guide how to do this -
https://youtu.be/LtMGmSSB52g

**Comment by sergius02** [comment]
> You'd have to configure fake wifi -
> 
> waydroid prop set persist.waydroid.fake_wifi packageName
> 
> I've created a guide how to do this - [youtu.be/LtMGmSSB52g](https://youtu.be/LtMGmSSB52g)

Works perfect, thanks!

**Comment by gagantous** [comment]
Hi @ryanrudolfoba  i am sorry for asking this, but do you know how to solve "wireless debugging" in developer mode ? i tried to set the toogle on but it's said "connect to your wifi" i tried what the instruction said but the wifi wont work. How to resolve this
