### ISSUE TITLE
Touch not working in games on steam deck

### ISSUE THREAD

**Issue by AliceBrightest** [ryanrudolfoba/SteamOS-Waydroid-Installer#41]
Hi, as the title says when i click in a game (though not in the android home menu) the click doesn't register, I've heard something called fake touch can rectify this but idk how to install it - please help

**Comment by ryanrudolfoba** [comment]
Which game so I can test?

**Comment by ryanrudolfoba** [comment]
Please follow this guide to configure fake touchscreen -

https://youtu.be/Xt2ceq8ZUJ8
