### ISSUE TITLE
Apps freeze and crash after awhile

### ISSUE THREAD

**Issue by Mario-119** [ryanrudolfoba/SteamOS-Waydroid-Installer#43]
I'm getting an odd issue where after an app has been open for an extended period of time, it freezes up and must be manually exited. Along with this, when that same app is re-opened it will simply freeze on the splashscreen and proceed to hang/freeze until it properly crashes. The only way to fix this is to restart waydroid completely. However even after doing so, the problem will always crop up again. 

I've done a fresh install of waydroid twice now, but sadly to no avail.

**Comment by ryanrudolfoba** [comment]
could be isolated to the app itself. what app so i can also test on my end?

**Comment by Mario-119** [comment]
> could be isolated to the app itself. what app so i can also test on my end?

It seems to happen not with one singular app, but with any app that has been open for awhile in the foreground. YouTube, Discord, Reddit, even the settings app. They freeze and remain frozen until the ANR popup appears. If you close the app and then try to go back into it, it either freezes or just endlessly loads

**Comment by NewRavenGer** [comment]
Actually, I came here to hopefully find a solution for the same issue. One app where this happens basically instantly is the GeForce Now app as soon as you try to actually launch a game. With other apps the timing seems to be more random. The netflix app, for example, I can sometimes run for hours and sometimes only minutes, but at some point, it will freeze and then crash. The weird thing is that clicking "wait for the app" doesn't seem to to anything, it crashes anyway, while "close" the app seem to close the app, but, as Mario-119 already said, if you try to restart it, it either endlessly loads or freezes right from the start.

**Comment by ryanrudolfoba** [comment]
I've updated the script. Major components are updated to newer versions - lxc, dnsmasq, waydroid etc etc.

Please test if you still get that behavior.

**Comment by ryanrudolfoba** [comment]
feel free to provide update if further help is needed.
