### ISSUE TITLE
Read-only file system when install

### ISSUE THREAD

**Issue by azaleascynics** [ryanrudolfoba/SteamOS-Waydroid-Installer#48]
![Screenshot_20240226_192550](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/149035535/4c5f39ba-ccd6-41a8-b545-00429ff947e0)

Tried few times but no luck
cp: cannot create regular file '/lib/modules/6.1.52-valve9-1-neptune-61/binder_linux.ko.zst': Read-only file system

**Comment by ryanrudolfoba** [comment]
this is similar to this issue - https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/45

please take a look in there

**Comment by ryanrudolfoba** [comment]
I will be closing this issue as this is not related to the script. Please feel free to re-open or create a new issue if you are having issues with the script.

**Comment by azaleascynics** [comment]
It works after updated the steamos and without any custom application like rclone, decky and tailscale. 
They shouldn't affect to disable the readonly mode but anyway thank you for your information and help !!

**Comment by ryanrudolfoba** [comment]
most probably tailscale is the culprit. Glad you got it sorted out.
