### ISSUE TITLE
[Feature Request] Mounting file system into Android partition

### ISSUE THREAD

**Issue by kudou-reira** [ryanrudolfoba/SteamOS-Waydroid-Installer#49]
Is it possible to access files in the Steam Deck `home` directory or the SD card from inside waydroid? Currently, it seems that when I go to the files app, I can only access directories local to the Android installation.

**Comment by floriegl** [comment]
You already can! https://docs.waydro.id/faq/setting-up-a-shared-folder

**Comment by kudou-reira** [comment]
Thanks so much!
