### ISSUE TITLE
Install blocked by new kernel version.

### ISSUE THREAD

**Issue by nadroj71** [ryanrudolfoba/SteamOS-Waydroid-Installer#51]
Please recompile for latest kernel version 6.1.52-valve17-1-neptune-61

**Comment by ryanrudolfoba** [comment]
What SteamOS version are you on?

I only build for Stable and Beta / Preview.

**Comment by nadroj71** [comment]
3.6. I got on the "main" update channel awhile back because I needed 3.6
for something that escapes me. Just now realized that the main channel is
the only one that is on 3.6.

</Jordan>

**Comment by LuckyPhilll** [comment]
6.1.52-valve17-1-neptune-61 is NOT supported. Exiting immediately.

**Comment by ryanrudolfoba** [comment]
Closing issue - i only build for SteamOS stable and Preview.
