### ISSUE TITLE
can't install on stable channel

### ISSUE THREAD

**Issue by zeia0819** [ryanrudolfoba/SteamOS-Waydroid-Installer#53]
lastest update kill my waydroid.
trying to reinstall but get the error : 6.1.52-valve16-1-neptune-61 is NOT supported. Exiting immediately.

**Comment by ryanrudolfoba** [comment]
The latest SteamOS stable 3.5.17 uses the same kernel from 3.5.16 so no need to update the existing script it works fine as is.

With that said maybe you have older version of the script. Make sure you are using the latest released last Feb 11 2024.
