### ISSUE TITLE
ERROR: Downloaded system image hash doesn't match

### ISSUE THREAD

**Issue by tGMR-Botclone** [ryanrudolfoba/SteamOS-Waydroid-Installer#54]
I'm getting an error while running the install script. I think these are the relevant lines.

```
Config file missing. Lets configure waydroid.
[19:35:15] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240224-GAPPS-waydroid_x86_64-system.zip/download
[Downloading]   9.24 MB/858.64 MB       0.99 kbps(approx.)[19:46:23] Validating system image
[19:46:23] ERROR: Downloaded system image hash doesn't match, expected: 9ac5727051c543b0eca80e2318e45ebe1894a0f43025397fcc99832c03ff7678
[19:46:23] See also: <https://github.com/waydroid>
 Run 'waydroid log' for details.
Waydroid did not initialize correctly. Performing cleanup!
```
I followed the guide as normal. Repo's already added prior, and I copy-pasted the second commands. I've also tried running those commands again and the results are the same.

Running 'waydroid log' returns a 'command not found.
I'm on the most recent SteamOS version 3.5.17 build 20240228.2 on an LCD model.

**Comment by ryanrudolfoba** [comment]
It means that the downloaded waydroid image from sourceforge got corrupted.

This could be due to slow Internet/ slow mirror and the download failed.

When this happens the script performs a cleanup. Just run the script again and it will retry to download the waydroid image.
