### ISSUE TITLE
Wireless debugging issue in waydroid steamos

### ISSUE THREAD

**Issue by gagantous** [ryanrudolfoba/SteamOS-Waydroid-Installer#55]
Hi! i am sorry for asking this, but do you know how to solve "wireless debugging" in developer mode ? i tried to set the toogle on but it's said "connect to your wifi" i tried what the instruction said but the the wifi seems not working. How to resolve this ?

**Comment by ryanrudolfoba** [comment]
Are you trying the mantis gamepad mapper for this?

afaik this wont work. Waydroid doesnt use wifi but instead uses the existing network connection of the Steam Deck (or the host machine). Without a working wifi you cant enable wireless debugging.

**Comment by gagantous** [comment]
yes, i tried to used gamepad mapper.
but thanks for the answer, now i know it wont work for the gamepad mapper.
