### ISSUE TITLE
Android_Waydroid_Cage.sh fails (undefined symbol: g_assertion_message_cmpint)

### ISSUE THREAD

**Issue by nickgirga** [ryanrudolfoba/SteamOS-Waydroid-Installer#59]
When running the "Android_Waydroid_Cage.sh" script, the wlroots window opens, but remains black and the terminal says the following:

```
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 5, in <module>
    from gi.repository import GLib
  File "/home/deck/.local/lib/python3.11/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /home/deck/.local/lib/python3.11/site-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so: undefined symbol: g_assertion_message_cmpint
```

I'm on the latest stable SteamOS version as of 3/21/24 (SteamOS 3.5.17) with no system modifications done (besides this Waydroid setup script). I do have Decky installed and use several non-standard apps for SteamOS via Distrobox, but I don't think these should play a role.

**Comment by ryanrudolfoba** [comment]
Please try this -
Go to Nested Desktop
Open konsole and run this command -
sudo waydroid-container-stop
sudo waydroid-container-start
waydroid show-fuill-ui

**Comment by nickgirga** [comment]
Okay, so I tried that and all of the commands you suggested to try were all invalid commands (maybe bc gaming mode has a slightly different environment with different env vars, so they may not have been in the PATH variable). But I did solve it. I will detail this in a separate comment.

**Comment by nickgirga** [comment]
The problem was the local Python packages/libraries that I had installed. I realized they were actually causing problems with other GTK-based apps. I went back to develop an app I was making with Python and pygobject (Python bindings for GTK) and it was giving me the exact same error. I think a new version of Python was installed on the system since the last time I was working on that app (because it worked fine before). This new version of Python is probably incompatible with the older Python packages/libraries that had been installed throughout the life of my Steam Deck.

So, to "solve" it, I basically just moved the `/home/deck/.local/lib/python3.11/site-packages` directory to `/home/deck/.local/lib/python3.11/site-packages.bak`. You can probably delete the directory, but I didn't want to lose all of those old packages entirely and I wasn't sure if it would just break more things. When I went back to test my app, it worked fine. Considering the exact samw error was popping up with this Waydroid implementation, I decided to reinstall it to see if that was also solved. It booted up just fine. My Waydroid works now.

And before you ask, I did try rebuilding the Python GI library (the one giving these complaints) with the new version of Python and that didn't work. Only "removing it entirely" (again, I just moved the directory) fixed it.

The reason I put "solve" in quotes is because I effectively uninstalled all of those Python packages/libraries. I'm going to have to reinstall them. Some people may be genuinely using some installed Python packages/libraries for other apps. I'm versed in Linux and Python, so solving this isn't a massive deal to me, but telling an average user "just delete the site-packages folder" could cause more unsolvable issues in other apps for them.

I would maybe put this as an answer in an FAQ somewhere, as some people might experience a similar problem, but I would definitely make it VERY clear the caveats of doing so, as (again) it might break more stuff for some people and they wouldn't necessarily know how to solve that unless they are familiar with Python and Linux.

Marking this issue as closed.

**Comment by ryanrudolfoba** [comment]
Thank you for the explanation of the issue. I'll add this to FAQ as this issue pops up from time to time.
