### ISSUE TITLE
[SteanOS 3.5.7] Controller Not Support

### ISSUE THREAD

**Issue by cnbleu** [ryanrudolfoba/SteamOS-Waydroid-Installer#6]
Hi @ryanrudolfoba, you do the great  job, thank  you  first. 

I followed your tutorial on YouTube and executed your script on my Steam Deck[LCD version]. Everything went smoothly. However, after entering the Android system, the controller test program couldn't detect the Xbox 360 controller. Is this a known issue? How can I resolve this problem? Looking forward to your reply.

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
