### ISSUE TITLE
error in installer

### ISSUE THREAD

**Issue by St1X89** [ryanrudolfoba/SteamOS-Waydroid-Installer#60]
error: RPC failed; curl 18 HTTP/2 stream 5 was resetKiB/s  
error: 336 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error cloning Casualsnek repo! Goodbye!

tried deleting, restarting. cant get it to install

**Comment by ryanrudolfoba** [comment]
internet connection could be slow and download got corrupted. i would suggest to re-run the install script.

**Comment by ryanrudolfoba** [comment]
havent heard back so closing this issue. please feel free to reopen if need further help.
