### ISSUE TITLE
64 bit only?

### ISSUE THREAD

**Issue by Malvalar** [ryanrudolfoba/SteamOS-Waydroid-Installer#61]
Is there a way to install Waydroid on the Deck so that it only has 64-bit architecture?

**Comment by ryanrudolfoba** [comment]
Thats possible but the app compatibility will be lower.

The script already bundles the libndk arm translation layer. You can remove it so it only has x86-64 support, is that what you are referring to?

**Comment by Malvalar** [comment]
In this case it's actually for compatibility. I have an app that's recently transitioned to only support x64

**Comment by ryanrudolfoba** [comment]
that should work - waydroid supports x86-64 apps. You can sideload the app too

**Comment by Malvalar** [comment]
True, I forgot about sideloading.
