### ISSUE TITLE
6.1.43-valve1-1-neptune-61 is NOT supported. Exiting immediately.

### ISSUE THREAD

**Issue by speed0urlj** [ryanrudolfoba/SteamOS-Waydroid-Installer#62]
Help

**Comment by ryanrudolfoba** [comment]
Looks like you are using an older version of SteamOS?

What version are you on?

**Comment by speed0urlj** [comment]
stable

**Comment by ryanrudolfoba** [comment]
That is an old stable version then.
I would suggest to update to the latest stable SteamOS.
