### ISSUE TITLE
uninstall script not installed 

### ISSUE THREAD

**Issue by neviohack** [ryanrudolfoba/SteamOS-Waydroid-Installer#64]
i tried to uninstall wayland because it would not launch but the uninstall script but it was not in /home/deck/Android_Waydroid/
![Screenshot_20240330_000734](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/150777120/b13b58ae-6189-4144-b951-1cb948539c69)
![Screenshot_20240330_000622](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/150777120/842df43b-6671-456d-90a0-564cbbaa4771)

**Comment by ryanrudolfoba** [comment]
The script went several updates. on the latest version of the script, please use waydroid toolbox GUI for extra stuff including the uninstall. I'll need to update the Github to reflect this info.

![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/98122529/069ac154-0090-45a4-9662-6726686bcfa4)

**Comment by ryanrudolfoba** [comment]
updated the github readme on how to uninstall using Waydroid Toolbox.
