### ISSUE TITLE
How to use adb connection ?

### ISSUE THREAD

**Issue by gagantous** [ryanrudolfoba/SteamOS-Waydroid-Installer#65]
I tried to used adb connection but it seems my adb command is not installed, do we have to install it separately ? or it'[s already included on your script ?

**Comment by ryanrudolfoba** [comment]
its not included. What do you need adb for?

**Comment by ryanrudolfoba** [comment]
I didnt include ADB in the script as i dont see a use for it at the moment.

you can install ADB manually if you need it. it is available in the pacman repos.
