### ISSUE TITLE
Feature Request: Custom Command on Startup

### ISSUE THREAD

**Issue by D3thRoned** [ryanrudolfoba/SteamOS-Waydroid-Installer#69]
Hey,

would it be possible to create a way to run a Custom Commands after booting android?

In my Case i tryd to get Mantis Pro working.
To do so the App needs to start the Server. Normaly doing so by Root/ADB or WIFI Debug.

I managed to make it run by executing the batch.sh inside the Mantis Android Folder via Shell.
But now i need to do it everytime.

So having a way to extend the Startup script with custom commands may be a good Feature not only for myuse case.
Like the App-Launching just with an Custom Command.

**Comment by ryanrudolfoba** [comment]
Yes I have that exactly for that use case - mantis pro and shizuku root. Been testing for several weeks now just to be sure no error. Gonna update soon.

**Comment by ryanrudolfoba** [comment]
Check the guide here about Mantis activation using startup script -

https://youtu.be/icVOh7IIfE0

This will be added to main script soon together with other goodies.
