### ISSUE TITLE
Warning: database file for 'xy' does not exist (use '-Sy' to download)

### ISSUE THREAD

**Issue by Nitsu29** [ryanrudolfoba/SteamOS-Waydroid-Installer#7]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
VERSION_ID=3.5.7
SteamOS 3.5.x detected. Proceed with the script.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
So far so good!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2023-12-18
Pacman has been initialized!
Cloning into '/home/deck/AUR/waydroid/waydroid'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 93 (delta 16), reused 93 (delta 16), pack-reused 0
Receiving objects: 100% (93/93), 23.22 KiB | 7.74 MiB/s, done.
Resolving deltas: 100% (16/16), done.
Cloning into '/home/deck/AUR/waydroid/binder_linux-dkms'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 54 (delta 11), reused 54 (delta 11), pack-reused 0
Receiving objects: 100% (54/54), 14.54 KiB | 7.27 MiB/s, done.
Resolving deltas: 100% (11/11), done.
Cloning into '/home/deck/AUR/waydroid/python-gbinder'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 39 (delta 8), reused 39 (delta 8), pack-reused 0
Receiving objects: 100% (39/39), 6.71 KiB | 6.71 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Cloning into '/home/deck/AUR/waydroid/libgbinder'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 56 (delta 21), reused 56 (delta 21), pack-reused 0
Receiving objects: 100% (56/56), 7.22 KiB | 7.22 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Cloning into '/home/deck/AUR/waydroid/libglibutil'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 48 (delta 15), reused 48 (delta 15), pack-reused 0
Receiving objects: 100% (48/48), 6.66 KiB | 6.66 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Cloning into '/home/deck/AUR/waydroid/waydroid_script'...
remote: Enumerating objects: 670, done.
remote: Counting objects: 100% (316/316), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 670 (delta 263), reused 237 (delta 217), pack-reused 354
Receiving objects: 100% (670/670), 21.72 MiB | 9.35 MiB/s, done.
Resolving deltas: 100% (411/411), done.
No errors encountered downloading from AUR.
warning: database file for 'jupiter-rel' does not exist (use '-Sy' to download)
warning: database file for 'holo-rel' does not exist (use '-Sy' to download)
warning: database file for 'core-rel' does not exist (use '-Sy' to download)
warning: database file for 'extra-rel' does not exist (use '-Sy' to download)
warning: database file for 'community-rel' does not exist (use '-Sy' to download)
warning: database file for 'multilib-rel' does not exist (use '-Sy' to download)
warning: database file for 'rumpowered' does not exist (use '-Sy' to download)
warning: database file for 'jupiter-staging' does not exist (use '-Sy' to download)
warning: database file for 'holo-staging' does not exist (use '-Sy' to download)
error: target not found: fakeroot
error: target not found: base-devel
error: target not found: glibc
error: target not found: glib2
error: target not found: linux-api-headers
error: target not found: linux-neptune-61-headers
error: target not found: python3
error: target not found: lxc
error: target not found: dnsmasq
error: target not found: weston
Error installing pacman dependencies. good bye!

**Comment by ryanrudolfoba** [comment]
i'm rewriting the script so it doesnt pull packages from the pacman repo. tested with binder module and it works. gonna continue with the rest of the script.

**Comment by ryanrudolfoba** [comment]
please check i've updated the repo. its much easier and quicker to install now, plus multi-touch works.
check the demo video too as need to uninstall first the old version. demo video also shows how to configure multi touch.

demo video -
https://www.youtube.com/watch?v=06T-h-jPVx8
