### ISSUE TITLE
60 FPS limit

### ISSUE THREAD

**Issue by Uncraftbar** [ryanrudolfoba/SteamOS-Waydroid-Installer#71]
I have a steam deck oled and it doesn't seem like android goes over 60 fps. I made sure I have no fps cap set. Is there a fix to this? It would be nice to have it running at 90 fps for the extra smoothness of the oleds screen

**Comment by Uncraftbar** [comment]
Okay, after updating the script and trying the 1080p tutorial it doesn't seem to work. Set it to 90 but it's still locked at 60

**Comment by ryanrudolfoba** [comment]
sorry for late reply. I think this is a waydroid limitation hard cap at 60fps.

**Comment by Xtr126** [comment]
It turns out by patching wlroots we can get around the 60FPS limit - it's not a hard cap but if the compositor doesn't provide a refresh rate higher than 60000 mHz it will default to 60 FPS. I've fixed this for cage-xtmapper https://github.com/Xtr126/cage-xtmapper/issues/2

**Comment by ryanrudolfoba** [comment]
Thanks I'll take a look.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
