### ISSUE TITLE
Sideloading apks on steam deck stuck at session start

### ISSUE THREAD

**Issue by rkichenama** [ryanrudolfoba/SteamOS-Waydroid-Installer#76]
SteamOS version - latest
Error message encountered - see below
Screenshot of error - see below
Do you have any scripts / tweaks that might be causing issues?

I followed the instructions and when I have the container started and trying to start a session the Android user 0 does not show up. I've waited several minutes and nothing changes. When I force close and restart, the Waydroid works but the controls are not picked up. The purpose of sideloading is to get the gamepad apk sideloaded to fix.

For one day prior to using the Wayland update within Waydroid, the controls worked without any additional work. Minecraft and Jetpack Joyride just worked, but when I updated the images, the controls stopped working.

**Comment by ryanrudolfoba** [comment]
it could be a flaky android update.

i would suggest to reinitialize waydroid -

sudo waydroid init -f -s GAPPS

**Comment by rkichenama** [comment]
No change after using that command before or after container start. Still hangs at Service manager appearing

**Comment by ryanrudolfoba** [comment]
Only thing i can think of is to uninstall Waydroid using Waydroid Toolbox, then reinstall to start over fresh.
