### ISSUE TITLE
unable to download data from Astra Knight of veda game

### ISSUE THREAD

**Issue by gagantous** [ryanrudolfoba/SteamOS-Waydroid-Installer#77]
hi! i cant download game data from this game, called "Astra knight of veda". did someone encounter this problem too?

![Screenshot_20240428_211220](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/24579576/dae3ec53-7f6c-48c9-9c5b-49c8ca0eddda)

**Comment by ryanrudolfoba** [comment]
Maybe it needs fake wifi?

**Comment by gagantous** [comment]
> Maybe it needs fake wifi?

okay i would try that

**Comment by gagantous** [comment]
```
(deck@steamdeck ~)$ waydroid app list | grep -i "astra" -A1
Name: Astra
packageName: com.hybeim.astra
categories:
(deck@steamdeck ~)$ waydroid app list | grep -i "astra" -A^C
(130)(deck@steamdeck ~)$ ^C
(130)(deck@steamdeck ~)$ ^C
(130)(deck@steamdeck ~)$ ^C
(130)(deck@steamdeck ~)$ waydroid app list | grep -i "veda" -A1
(1)(deck@steamdeck ~)$ waydroid prop set persist.waydroid.fake_wifi com.hybeim.astra
(deck@steamdeck ~)$ waydroid session stop
(deck@steamdeck ~)$ sudo waydroid-container-stop
(deck@steamdeck ~)$ 
```

i have done that, but its not working

**Comment by ryanrudolfoba** [comment]
could be a game compatibility itself. only thing i can think of is install on a regular android device, then copy the obb data to waydroid.
