### ISSUE TITLE
Config file missing. Lets configure waydroid.

### ISSUE THREAD

**Issue by m1gcrz** [ryanrudolfoba/SteamOS-Waydroid-Installer#80]
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/58041068/6ac4e699-e4a5-4bc6-9d05-e0ca08e6470b)

![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/58041068/3de78727-919c-44db-bdad-94ea88a388cc)

fresh reimage, only chrome and firefox browsers are installed, waited for quite a while

**Comment by ryanrudolfoba** [comment]
Config file is missing is normal on a fresh install, but it shouldn't get stuck in there for a long while.

It will try to download Waydroid image from the internet. Try to run the script again maybe it is having issues connecting to the server to download.
