### ISSUE TITLE
New OS and Kernel Version for the Beta Channel

### ISSUE THREAD

**Issue by smabbage** [ryanrudolfoba/SteamOS-Waydroid-Installer#81]
Steam has updated the OS and kernel versions for the beta channel.  

Old OS Version - 3.5.19
New OS Version - 3.6

Old Kernel Version - 6.1.52-valve16-1-neptune-61 
New Kernel Version - 6.5.0-valve5-1-neptune-65-g6efe817cc486

Waydroid no longer loads.

**Comment by ryanrudolfoba** [comment]
Need to build kernel modules to match the new kernel in SteamOS Preview.

Problem is some other things are broken on SteamOS 3.6 and im afraid I'd have to rewrite the script :(

I'll wait for the dust to settle maybe on next beta / preview release they will fix it then I'll build the kernel module.

**Comment by smabbage** [comment]
Thanks for the update.  I'll leave waydroid in the menu and wait on the new kernel module.

**Comment by smabbage** [comment]
New install went off without a hitch.  Took a little longer than usual but all was good, just needed to exercise a little patience.  Thanks for the update.
