### ISSUE TITLE
Fake Wifi [Wayland Display is not set]

### ISSUE THREAD

**Issue by BeeperMiniSourceCode** [ryanrudolfoba/SteamOS-Waydroid-Installer#85]
![image](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/154485916/953c1b17-05be-4665-958d-f7ac2cc23ba3)
Here I am again with another error. Waydroid is installed and I checked but when I do waydroid session start it says this. I don't know what to do.

**Comment by BeeperMiniSourceCode** [comment]
This image is stolen from another issue opened but it's exactly the same thing.

**Comment by ryanrudolfoba** [comment]
I've created a guide regarding fake wifi -

https://youtu.be/LtMGmSSB52g

This needs to be done on Nested Desktop.

**Comment by rezzafr33** [comment]
If waydroid still can't access internet even after setting up fake wifi, probably you need to redo firewall setup. https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/blob/060a374d352a514b1f78d4c0a6e3149fb22359a3/steamos-waydroid-installer.sh#L291
