### ISSUE TITLE
dbus Error When Installing

### ISSUE THREAD

**Issue by BuberQT3dragon** [ryanrudolfoba/SteamOS-Waydroid-Installer#87]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
Warning: The rootfs is already read-write!
         Nothing is performed.
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-06-29
pacman keyring has been initialized!
binder kernel module already loaded! no need to reinstall binder!
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly
Most probably this is due to python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python /home/deck/.cache/activestate/bin/python /usr/share/man/man1/python.1.gz
Output of which python - /home/deck/.cache/activestate/bin/python
Output of python version - Python 3.10.11
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

[Comments]
I looked at issue #42, it doesn't provide a direct solution.
I looked at issue #50, which is a link to issue #42.
I looked at issue #63, which is a another link to the two above issues.
I looked at issue  #74, but my Python isn't in the miniconda3 folder even though I do have EmuDeck.

If my version of Python is abnormal, I most likely did a manual update, if there was a way to manually downgrade I may be able to get it fixed. I have a folder on my home/deck folder named "Python-3.10.11-Linux-CentOS". I removed it, attempted the install, but it still failed showing my Python version as 3.10.11 still. I have experienced MANY SteamOS updates since having this issue, and I haven't touched Konsole in months until now.

below is a list of 3rd-Party applications I have installed that could potentially be affecting my Python.

[List of Applications]
EmuDeck
CryoUtilities
Decky
JavaScript 3 (jdk-17-jre)
Battle Cats Ultimate
Honkers Railway Launcher
Honkers Launcher
An Anime Game Launcher

**Comment by ryanrudolfoba** [comment]
this is the offending line -

> Output of which python - /home/deck/.cache/activestate/bin/python

it means that you have another python installed on your system which is interfering with Waydroid.

the script doesnt depend on 3rd party python - it just uses the one that came with SteamOS.

i dont know what the behavior will be when you remove that python - it might break other apps on your system.

unfortunately i dont use the apps you installed (except for decky loader) so i dont know what the behavior will be.

**Comment by BuberQT3dragon** [comment]
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.1.52-valve16-1-neptune-61 is supported. Proceed to next step.
Please enter current sudo password: 
Checking if the sudo password is correct.
Sudo password is good!
Casualsnek repo has been successfully cloned!
==> Appending keys from archlinux.gpg...
==> Appending keys from holo.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-06-29
pacman keyring has been initialized!
binder kernel module already loaded! no need to reinstall binder!
waydroid and cage has been installed!
Config file missing. Lets configure waydroid.
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
Waydroid did not initialize correctly
Most probably this is due to python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python /usr/share/man/man1/python.1.gz
Output of which python - /usr/bin/python
Output of python version - Python 3.11.3
Something went wrong! Performing cleanup. Run the script again to install waydroid.
Cleanup completed. Please open an issue on the GitHub repo or leave a comment on the YT channel - 10MinuteSteamDeckGamer.

After removing that installation of Python, I now get the same error with a different source and version of Python. If fixing the error requires me to remove another Python file, I'm afraid I'll have to abandon my attempts to install waydroid as the Dolphin file explorer doesn't let me delete or remove any files within the /usr folder.

**Comment by ryanrudolfoba** [comment]
this is out of scope for the script. script uses the built-in python that came with SteamOS. 3rd party python installs will cause issues.
