### ISSUE TITLE
Steam Deck Waydroid Installer Error

### ISSUE THREAD

**Issue by LobsterClawed** [ryanrudolfoba/SteamOS-Waydroid-Installer#88]
[Waydroid Error Log.txt](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/files/15417234/Waydroid.Error.Log.txt) 

SteamOS 3.5.19

"ERROR: Downloaded vendor image hash doesn't match, expected: ece31f8558065bf063f0c93adb52ca8c9bce20dbde7a64237b7cd21bbcf46313
[08:58:55] See also: <https://github.com/waydroid>
 Run 'waydroid log' for details.
Waydroid did not initialize correctly
Most probably this is due to python issue. Attach this screenshot when filing a bug report!
Output of whereis python - python: /usr/bin/python
Output of which python - /usr/bin/python
Output of python version - Python 3.11.3"
![Error Screenshot](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/143207649/623e7434-a80f-42d5-9686-e760e0a00ea6)

**Comment by ryanrudolfoba** [comment]
based on the error message it looks like it is a corrupted download of the image. i would suggest to run the script again.
