### ISSUE TITLE
Error cloning Casualsnek Repo

### ISSUE THREAD

**Issue by MezMez** [ryanrudolfoba/SteamOS-Waydroid-Installer#89]
Retried 5 times by now, no dice
![Screenshot_20240524_000047](https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/assets/8093323/8259e3ec-9c9a-4755-bf45-cadec8e86351)

**Comment by ryanrudolfoba** [comment]
You mean the Wuthering Waves? Yes it works on Waydroid I've played it for a bit.

**Comment by MezMez** [comment]
Yeah, unfortunately still no dice... ;_;
Well, its fine, I'll just have to put up with 3 year old phone performance until it works...

**Comment by ryanrudolfoba** [comment]
try this please i just made an update. script will now download from backup casualsnek repo if the first clone fails.

clone this repo again to get the latest version of the script and run the install. let me know how it goes.
