### ISSUE TITLE
provide how-to to compile binder-modules

### ISSUE THREAD

**Issue by slynobody** [ryanrudolfoba/SteamOS-Waydroid-Installer#90]
please provide a how-to: compile binder-modules.

in that way the community has the opportunity to supply modules for all the steam-os-versions out there.
someone could even write a script to auto-compile modules locally at first installation.

**Comment by ryanrudolfoba** [comment]
You could build the binder kernel module using the steps 1.4.2 dkms module -

https://wiki.archlinux.org/title/Waydroid

SteamOS 3.6 binder kernel module uploaded.

**Comment by ryanrudolfoba** [comment]
>  someone could even write a script to auto-compile modules locally at first installation.

This is a good idea - i'll try update the script to add ti compile the binder kernel module
