### ISSUE TITLE
Missing nodataperm.sh

### ISSUE THREAD

**Issue by killua99** [ryanrudolfoba/SteamOS-Waydroid-Installer#93]
Thanks for this repo.

altho I found an issue with the current installer, the `extras/nodataperm.sh` is missing on the cp * sequence then the cage script launcher is trying to trigger it, failing.

**Comment by ryanrudolfoba** [comment]
thanks for pointing it out. please clone the repo again to get the latest version of the install script, or manually copy extras/nodataperm.sh to /var/lib/waydroid/overlay/system/etc

**Comment by killua99** [comment]
yes I noticed some problems, I did that by myself before writing down this issue.

I'm trying to run wuthering waves but the game keep crashing, I guess something related to the hardware emulation

**Comment by ryanrudolfoba** [comment]
for wuthering waves they made changes after an update and it doesnt work anymore.
