### ISSUE TITLE
Pokemon Unite unable to login

### ISSUE THREAD

**Issue by colinator19** [ryanrudolfoba/SteamOS-Waydroid-Installer#95]
When running Pokemon Unite on the Steam Deck, I want to login with my Nintendo account which goes fine, the login browser closes but then I just see the text “loading…” on top of the login screen.

it remains there forever and does not continue into the game.

tried to reinstall and force kill but no luck. Same thing happens when trying to use the guest account.

**Comment by fowlmanor** [comment]
Sending with me, we will just have to remote into PC for now.

**Comment by ryanrudolfoba** [comment]
Sorry for late reply. This could be due to anti cheat.
