### ISSUE TITLE
Fortnite not supported

### ISSUE THREAD

**Issue by Hellacia** [ryanrudolfoba/SteamOS-Waydroid-Installer#99]
Is there a way to get fortnite working? This is the one huge game that isn't supported on the deck already so it'd be nice to have it running through waydroid

**Comment by ryanrudolfoba** [comment]
most probably because of the anti cheat.

**Comment by StellaLovesTech** [comment]
(sorry for talking in a old issue) but fortnite's anti cheat wont kick you out for playing in a vm with android

mac users used to play on a android vm to play the latest fortnite, i also got fortnite itself launching on waydroid with libndk
![image](https://github.com/user-attachments/assets/b37b5d23-0787-46df-8c2f-67f818e01a37)

however after installing, it just segfaults when launching, not the anti cheat, in theory the people at waydroid could fix it and fortnite would possibly be playable on the steam deck(and other linux devices)

**Comment by StellaLovesTech** [comment]
me and some person have gotten it not to crash

you have to use libhoudini, rename libhoudini to "libhou.so" at /var/lib/waydroid/overlay/system/{lib,lib64

then in the waydroid_base.prop add/edit this line 
ro.dalvik.vm.native.bridge=libhou.so

**Comment by ryanrudolfoba** [comment]
> me and someone have gotten it not to crash
> 
> you have to use libhoudini, rename libhoudini to "libhou.so" at /var/lib/waydroid/overlay/system/{lib,lib64
> 
> then in the waydroid_base.prop add/edit this line ro.dalvik.vm.native.bridge=libhou.so

Are you testing on Steam Deck? Its tricky to get libhoudini as the `/var` partition is tiny it doesnt fit

**Comment by ryanrudolfoba** [comment]
thata an issue with SteamOS - the var partition is tiny so we can only use libndk at the moment. It eeror when using libhoudini it doesnt fit. On Bazzite this is all good can use libhoudini without error.

**Comment by StellaLovesTech** [comment]
hi, do you mind deleting the comment replying to mine as it may get patched by epic eventually?
